/* ============================================================
   DATOS DEL ANEXO — este es el unico archivo que necesitas
   tocar para agregar o corregir contenido del libro.
   No hace falta saber programar: copia el formato de una
   entrada existente y cambia el texto entre comillas.

   ERAS         -> los grandes bloques de la cronologia
   CRONOLOGIA   -> cada episodio (era, marca, titulo, resena, ver)
   GENERACIONES -> los bloques del arbol genealogico
   FIGURAS      -> cada personaje (id, n, rol, epi, gen, padres,
                   pareja, r = resena, v = variantes, img = imagen)

   El campo "img" es opcional: la ruta de una ilustracion o
   fotografia para esa figura, por ejemplo img:"imagenes/gea.jpg".
   Guarda los archivos en una carpeta "imagenes" junto a este
   archivo y subela igual que los demas. Si una figura no lo
   tiene, el sitio muestra su inicial dentro del circulo, asi
   que puedes ir agregando ilustraciones de a poco. Conviene
   que sean cuadradas, de unos 400x400 pixeles.

   El campo "v" es opcional: uselo para discrepancias entre
   fuentes, nombres alternativos y versiones minoritarias. Se
   muestra aparte, en letra mas chica, debajo de la resena.

   Regla unica: el "id" de cada figura debe ser unico y sin
   tildes ni espacios, porque es el que usan "padres",
   "pareja" y "ver" para enlazar unos con otros.
   ============================================================ */

const ERAS = [
 {id:"e1", num:"Era I",  titulo:"Antes del tiempo", sub:"El vacío y los primordiales"},
 {id:"e2", num:"Era II", titulo:"El reino de Crono", sub:"Primera generación divina"},
 {id:"e3", num:"Era III",titulo:"El orden olímpico", sub:"Zeus impone su ley"},
 {id:"e4", num:"Era IV", titulo:"La edad de los héroes", sub:"Mortales con sangre divina"},
 {id:"e5", num:"Era V",  titulo:"Troya y el ocaso", sub:"El fin de la raza heroica"}
];

const CRONOLOGIA = [
 {era:"e1", marca:"Origen", titulo:"El Caos", resena:"No es desorden sino abertura: una sima bostezante donde todavía no hay arriba ni abajo. Hesíodo lo pone primero porque todo lo demás necesita un lugar donde caber.", ver:["caos"]},
 {era:"e1", marca:"Origen", titulo:"Nacen los primordiales", resena:"Del Caos surgen Gea (la tierra), Tártaro (el abismo bajo ella), Eros (la fuerza que une), Érebo (la sombra) y Nix (la noche). Son potencias, no personas: nadie les reza, todos los heredan.", ver:["gea","tartaro","eros","erebo","nix"]},
 {era:"e1", marca:"Origen", titulo:"Gea engendra sola", resena:"Sin unión previa, la tierra produce a Urano (el cielo estrellado), las montañas y Ponto (el mar). Es el primer acto de creación por desdoblamiento: la tierra fabrica aquello que la cubrirá.", ver:["urano","ourea","ponto"]},
 {era:"e1", marca:"Origen", titulo:"Los hijos encerrados", resena:"De Gea y Urano nacen doce titanes, tres cíclopes y tres hecatónquiros de cien brazos. Urano teme a los monstruosos y los devuelve al vientre de su madre, que empieza a fraguar la venganza.", ver:["ciclopes","hecatonquiros"]},
 {era:"e1", marca:"Ruptura", titulo:"La castración de Urano", resena:"Crono, el menor de los titanes, siega a su padre con una hoz de pedernal que Gea le entrega. Unas gotas de sangre caen sobre la tierra y dejan a Gea encinta de tres progenies: las Erinias, los Gigantes y las Melias. De la espuma del mar donde cae el sexo nace, en cambio, Afrodita.", ver:["crono","urano","erinias","gigantes","melias","afrodita"]},

 {era:"e2", marca:"Edad de oro", titulo:"Crono devora a sus hijos", resena:"Advertido de que un hijo suyo lo destronará como él destronó a su padre, Crono traga a cada recién nacido. El ciclo del mito griego se anuncia aquí: ningún poder logra impedir su propio relevo.", ver:["crono","rea"]},
 {era:"e2", marca:"Edad de oro", titulo:"El engaño de Rea", resena:"Rea da a luz a Zeus en secreto en una cueva de Creta y entrega a Crono una piedra envuelta en pañales. El niño crece amamantado por la cabra Amaltea, entre los golpes de los Curetes que ahogan su llanto.", ver:["rea","zeus"]},
 {era:"e2", marca:"Guerra", titulo:"Zeus libera a sus hermanos", resena:"Ya adulto, Zeus hace vomitar a Crono a los cinco hijos devorados: Hestia, Deméter, Hera, Hades y Poseidón. Salen adultos y en orden inverso, así que el hermano menor es también el primogénito.", ver:["zeus","hestia","demeter","hera","hades","poseidon"]},
 {era:"e2", marca:"Guerra", titulo:"La Titanomaquia", resena:"Diez años de guerra entre olímpicos y titanes. Zeus libera del Tártaro a los cíclopes, que le forjan el rayo, el tridente a Poseidón y el casco de invisibilidad a Hades; los hecatónquiros sepultan a los titanes bajo una lluvia de rocas.", ver:["zeus","ciclopes","hecatonquiros"]},
 {era:"e2", marca:"Reparto", titulo:"El sorteo del cosmos", resena:"Los tres hermanos echan suertes: a Zeus el cielo, a Poseidón el mar, a Hades el mundo subterráneo. La tierra y el Olimpo quedan en común, y esa ambigüedad alimentará casi todos los conflictos posteriores.", ver:["zeus","poseidon","hades"]},

 {era:"e3", marca:"Amenaza", titulo:"La Gigantomaquia", resena:"Gea lanza contra los olímpicos a los Gigantes nacidos de la sangre de Urano. Un oráculo advierte que ningún dios puede matarlos sin la ayuda de un mortal: Heracles dispara la flecha que decide la guerra.", ver:["gea","heracles","zeus"]},
 {era:"e3", marca:"Amenaza", titulo:"Tifón contra Zeus", resena:"El último hijo de Gea, con cien cabezas de serpiente, arrasa el Olimpo y llega a arrancarle a Zeus los tendones. Vencido, queda aplastado bajo el Etna, y su aliento sigue saliendo por el cráter.", ver:["zeus","gea"]},
 {era:"e3", marca:"Humanidad", titulo:"El robo del fuego", resena:"Prometeo engaña a Zeus en el reparto del sacrificio y luego roba el fuego para los hombres en una caña hueca. Su castigo es el águila que le devora el hígado cada día en el Cáucaso.", ver:["prometeo","zeus"]},
 {era:"e3", marca:"Humanidad", titulo:"Pandora abre la jarra", resena:"Como represalia, Zeus envía a la primera mujer con una vasija que contiene todos los males. Cuando la abre solo queda dentro la esperanza, y los griegos nunca se pusieron de acuerdo sobre si eso es un consuelo o una condena.", ver:["epimeteo","zeus"]},
 {era:"e3", marca:"Estaciones", titulo:"El rapto de Perséfone", resena:"Hades se lleva a la hija de Deméter al inframundo mientras ella recoge flores en compañía de las oceánides; la madre, buscándola, deja morir toda cosecha. El pacto final —seis granos de granada, unos meses arriba y otros abajo— explica el invierno y funda los misterios de Eleusis.", ver:["hades","persefone","demeter","oceanides"]},
 {era:"e3", marca:"Humanidad", titulo:"El diluvio de Deucalión", resena:"Harto de la edad de bronce, Zeus anega la tierra. Sobreviven Deucalión, hijo de Prometeo, y Pirra, que repueblan el mundo lanzando piedras por encima del hombro: los huesos de la madre tierra se vuelven hombres.", ver:["prometeo","zeus"]},

 {era:"e4", marca:"Generación I", titulo:"Perseo y la Gorgona", resena:"Con las sandalias aladas, el casco de Hades y un escudo pulido como espejo, decapita a Medusa sin mirarla. De su cuello brota Pegaso, y la cabeza cortada seguirá petrificando enemigos hasta terminar en el escudo de Atenea.", ver:["perseo","atenea"]},
 {era:"e4", marca:"Generación II", titulo:"Los doce trabajos de Heracles", resena:"Enloquecido por Hera, mata a su familia; la expiación son doce tareas imposibles al servicio de Euristeo, del león de Nemea al perro Cerbero. Es el único héroe que termina sentado entre los dioses.", ver:["heracles","hera","hesperides"]},
 {era:"e4", marca:"Generación II", titulo:"Teseo y el Minotauro", resena:"Se ofrece como uno de los catorce jóvenes tributados a Creta y mata a la bestia del laberinto guiado por el hilo de Ariadna. Al volver olvida cambiar las velas negras, y su padre Egeo se arroja al mar que lleva su nombre.", ver:["teseo","minos","poseidon"]},
 {era:"e4", marca:"Generación II", titulo:"Los Argonautas", resena:"Jasón reúne a la primera tripulación de héroes para traer el vellocino de oro desde la Cólquide. Lo consigue por la hechicería de Medea, y el precio de esa deuda destruirá después a los dos.", ver:["orfeo","heracles"]},
 {era:"e4", marca:"Generación II", titulo:"La maldición de Tebas", resena:"Edipo resuelve el enigma de la Esfinge sin resolver el suyo: mata a su padre y desposa a su madre. La ciudad arrastrará la culpa hasta la guerra de los Siete contra Tebas y la desobediencia de Antígona.", ver:["dioniso"]},

 {era:"e5", marca:"Chispa", titulo:"La manzana de la discordia", resena:"A las bodas de Peleo y Tetis acuden todos los dioses salvo Eris, que arroja una manzana dedicada a la más bella. La disputa entre Hera, Atenea y Afrodita queda en manos de un pastor troyano.", ver:["eris","peleo","tetis-n","afrodita","hera","atenea"]},
 {era:"e5", marca:"Chispa", titulo:"El juicio de Paris", resena:"Cada diosa ofrece un soborno: poder, victoria en la guerra o la mujer más bella del mundo. Paris elige a Afrodita, se lleva a Helena de Esparta y arrastra consigo a mil naves.", ver:["afrodita","helena"]},
 {era:"e5", marca:"Guerra", titulo:"Diez años ante Ilión", resena:"La Ilíada no cuenta la guerra entera sino unas semanas del noveno año: la cólera de Aquiles, la muerte de Patroclo y el rescate del cuerpo de Héctor. Los dioses combaten en ambos bandos.", ver:["aquiles","zeus","atenea","apolo"]},
 {era:"e5", marca:"Caída", titulo:"El caballo y el saqueo", resena:"La astucia de Odiseo termina lo que diez años de asedio no pudieron. La ciudad arde, los templos se profanan y esa impiedad condena a los propios vencedores en el viaje de vuelta.", ver:["atenea","poseidon"]},
 {era:"e5", marca:"Regresos", titulo:"Los nostoi y la Odisea", resena:"Casi ningún héroe llega bien a casa: Agamenón cae asesinado al cruzar su umbral y Odiseo tarda otros diez años entre cíclopes, hechiceras y muertos. El regreso resulta más caro que la guerra.", ver:["poseidon","atenea"]},
 {era:"e5", marca:"Final", titulo:"El fin de la edad heroica", resena:"Orestes es absuelto por un tribunal humano y no por los dioses: la venganza cede ante la ley. Los semidioses se extinguen, Eneas huye hacia occidente y comienza la edad de hierro, la nuestra.", ver:["eneas","atenea"]}
];

const GENERACIONES = [
 {id:"g1", titulo:"Primordiales"},
 {id:"gn", titulo:"Prole de la Noche"},
 {id:"gm", titulo:"Estirpe de Ponto"},
 {id:"g2", titulo:"Titanes"},
 {id:"g3", titulo:"Segunda generación titánica"},
 {id:"g4", titulo:"Olímpicos"},
 {id:"g5", titulo:"Héroes y semidioses"},
 {id:"gt", titulo:"Linaje de Ío · Fenicia, Tebas y Creta"},
 {id:"ga", titulo:"Casa de Argos"},
 {id:"ge", titulo:"Casa de Esparta"},
 {id:"gf", titulo:"Casa de Ftía · los Eácidas"}
];

/* padres: ids · pareja: ids (uniones notables) */
const FIGURAS = [
 {id:"caos", n:"Caos", rol:"Primordial", epi:"La sima que se abre", gen:"g1", padres:[],
  r:"El primer principio: un hueco bostezante, sin forma ni límite. No engendra por unión sino por simple aparición, y de él salen la noche y la sombra."},
 /* ejemplo con ilustracion:
    {id:"ejemplo", n:"Nombre", rol:"Rol", epi:"Epiteto", gen:"g1", padres:["caos"],
     img:"imagenes/nombre.jpg", r:"Resena...", v:"Variantes..."},  */
 {id:"gea", n:"Gea", rol:"Primordial", epi:"La tierra de amplio pecho", gen:"g1", padres:["caos"], pareja:["urano","ponto","tartaro"],
  r:"Suelo firme y madre de casi todo lo que existe. Sin intervención masculina engendra primero a Urano, el mayor y más importante de sus hijos, y a continuación dos rasgos de su propia topografía que pueden entenderse como distintos de ella: las Montañas y el mar profundo, Ponto. Con cada uno de esos dos varones funda después una familia de signo contrario. Unida a Urano levanta la principal, la estirpe de la que saldrán los titanes y, tras ellos, los dioses olímpicos. Unida a Ponto levanta una menor y de naturaleza marítima, poblada de dioses del mar, ninfas y criaturas grotescas que quedarán por necesidad al margen del Olimpo. Es además la conspiradora perpetua: arma a Crono contra Urano, y después a los Gigantes y a Tifón contra Zeus."},
 {id:"tartaro", n:"Tártaro", rol:"Primordial", epi:"El abismo bajo la tierra", gen:"g1", padres:["caos"], pareja:["gea"],
  r:"Tan lejos del suelo como el suelo del cielo: un yunque tardaría nueve días en caer. Es cárcel de los titanes y, con Gea, padre de Tifón."},
 {id:"eros", n:"Eros", rol:"Primordial", epi:"El que afloja los miembros", gen:"g1", padres:["caos"],
  r:"En la versión antigua no es el niño con arco sino la fuerza más vieja del mundo: sin él nada se une y la creación se detiene."},
 {id:"erebo", n:"Érebo", rol:"Primordial", epi:"La tiniebla", gen:"g1", padres:["caos"], pareja:["nix"],
  r:"La oscuridad densa que ocupa el espacio entre la tierra y el mundo de los muertos. Unido a su hermana Nix engendra a Éter y a Hémera, y ahí termina su papel: la restante descendencia de la Noche la concibe ella sola."},
 {id:"nix", n:"Nix", rol:"Primordial", epi:"La noche", gen:"g1", padres:["caos"], pareja:["erebo"],
  r:"De su hermano Érebo tiene solo dos hijos, Éter y Hémera, las dos formas de la luz. Todo el resto de su nutrida descendencia lo engendra sola, sin intervención masculina, y es de signo contrario: el Sueño, la Muerte, las Moiras, la Discordia y los demás poderes que ningún dios puede revocar. Hasta Zeus la respeta; la Ilíada cuenta que se abstuvo de ofenderla por temor."},
 {id:"hemera", n:"Hémera", rol:"Primordial", epi:"El día", gen:"gn", padres:["erebo","nix"],
  r:"La luz diurna en persona, nacida de la tiniebla y de la noche en el mismo parto que su hermano Éter: para los griegos el día procede de lo oscuro y no al revés. Hesíodo las sitúa a ella y a su madre en un mismo umbral que nunca cruzan juntas, saludándose al pasar mientras una entra y la otra sale."},
 {id:"eter", n:"Éter", rol:"Primordial", epi:"La luminosidad de las alturas", gen:"gn", padres:["erebo","nix"],
  r:"El aire superior, purísimo y encendido, que respiran los dioses, frente al aire denso y bajo que respiran los mortales. Hermano de Hémera y nacido con ella del mismo parto, es más sustancia del cielo que personaje con relatos propios:",
  v:"Hesíodo lo nombra y no vuelve a ocuparse de él. Higino invierte el orden y hace de Éter y Hémera los padres de la tierra, el cielo y el mar."},
 {id:"moro", n:"Moro", rol:"Hijo de la Noche", epi:"El destino", gen:"gn", padres:["nix"],
  r:"Encabeza la lista de los hijos que la Noche engendra sola, y Hesíodo lo llama odioso. No es el destino en general sino algo más estrecho y más temible: la muerte ya señalada para un hombre concreto, la que le toca y de la que no hay apelación. Comparte raíz con la moira que cada mortal recibe al nacer."},
 {id:"ker", n:"Ker", rol:"Hija de la Noche", epi:"La Perdición", gen:"gn", padres:["nix"],
  r:"La negra Ker, la ruina que se lleva al hombre en el instante final. En la Ilíada, Zeus pone en la balanza las keres de Aquiles y de Héctor, y el plato que baja decide quién muere.",
  v:"Suele aparecer multiplicada en plural, las Keres, espíritus de la muerte violenta que merodean el campo de batalla y beben la sangre de los caídos."},
 {id:"tanato", n:"Tánato", rol:"Hijo de la Noche", epi:"La Muerte", gen:"gn", padres:["nix"],
  r:"La muerte en persona, inflexible y sin ofrendas: es el único dios al que no se le levantan templos porque no acepta regalos. Hermano de Hipno, con quien transporta el cuerpo de Sarpedón desde Troya hasta Licia en la Ilíada. Sísifo llegó a encadenarlo, y mientras estuvo preso nadie en el mundo pudo morir."},
 {id:"hipno", n:"Hipno", rol:"Hijo de la Noche", epi:"El Sueño", gen:"gn", padres:["nix"],
  r:"Hermano gemelo de Tánato y mucho más benigno: el sueño es la muerte que suelta a su presa cada mañana. En la Ilíada, Hera lo soborna para que adormezca a Zeus en pleno combate, y él acepta solo tras exigir como pago a una de las Gracias. De él nacen los Sueños que visitan a los durmientes."},
 {id:"geras", n:"Geras", rol:"Hijo de la Noche", epi:"La Vejez", gen:"gn", padres:["nix"],
  r:"El envejecer como potencia autónoma y no deseada, hermano de la Muerte y de la Perdición. Apenas tiene relatos, pero la cerámica ática lo representa como un viejo encogido y reseco que forcejea con Heracles, la imagen del héroe peleando contra lo único que no puede vencer."},
 {id:"oneiros", n:"Los Oneiros", rol:"Hijos de la Noche", epi:"Los Sueños", gen:"gn", padres:["nix"],
  r:"La tribu innumerable de los sueños. Salen de dos puertas: los que pasan por la de cuerno se cumplen, los que pasan por la de marfil engañan, y el durmiente no tiene manera de saber por cuál entró el suyo.",
  v:"Hesíodo los cuelga de la Noche; Homero, en cambio, los hace depender de Hipno. Zeus se vale de uno de ellos para mandar a Agamenón un sueño falso al comienzo de la Ilíada."},
 {id:"oizys", n:"Oizys", rol:"Hija de la Noche", epi:"El Dolor", gen:"gn", padres:["nix"],
  r:"La angustia y la miseria sostenidas, el sufrimiento que no es herida sino desgaste. Los romanos la tradujeron como Miseria. No protagoniza mito alguno: su fuerza está justamente en ser el fondo cotidiano contra el que se recortan las hazañas de los héroes."},
 {id:"apate", n:"Apate", rol:"Hija de la Noche", epi:"El Engaño", gen:"gn", padres:["nix"],
  r:"El fraude y la mentira eficaz, hermana de la Discordia y del Dolor. Los griegos no la condenaban sin matices: el engaño que Zeus sufre de Hera, o el que Odiseo emplea en Troya, pertenece al mismo terreno que ella gobierna. Escapa de la jarra de Pandora junto con los demás males."},
 {id:"nemesis", n:"Némesis", rol:"Hija de la Noche", epi:"El castigo merecido", gen:"gn", padres:["nix"],
  r:"No es venganza ni azar, sino la corrección de lo desmedido: reparte a cada uno lo que le corresponde y recorta al que tiene de más o se envanece de más. Persigue sobre todo la soberbia del afortunado.",
  v:"Una tradición la hace madre de Helena: perseguida por Zeus y transformada en oca, puso el huevo que Leda solo habría criado. Otra, al revés, deifica a Leda como Némesis después de su muerte."},
 {id:"eris", n:"Eris", rol:"Hija de la Noche", epi:"La Discordia", gen:"gn", padres:["nix"],
  r:"La querella y la rivalidad. Hesíodo distingue dos: una ruinosa, que alimenta la guerra, y otra provechosa, que empuja al alfarero a competir con el alfarero. Es ella quien, excluida de las bodas de Peleo y Tetis, arroja la manzana que desata la guerra de Troya."},
 {id:"filotes", n:"Filotes", rol:"Hija de la Noche", epi:"La ternura", gen:"gn", padres:["nix"],
  r:"Su nombre significa amistad y afecto, y también el trato amoroso. Es la única de la prole de la Noche que no es un mal, aunque Hesíodo la coloca entre el Engaño y la Vejez: el cariño nace de la misma oscuridad que la discordia, y para los griegos esa vecindad no era una contradicción sino una advertencia."},
 {id:"hesperides", n:"Las Hespérides", rol:"Hijas de la Noche", epi:"Las hijas de la Tarde", gen:"gn", padres:["nix"],
  r:"Grupo de ninfas que habita el jardín de los dioses, en los confines occidentales de la tierra. Custodian allí, con el dragón Ladón, un árbol maravilloso que da manzanas doradas. Su nombre viene de Héspero, la estrella de la tarde, y su lugar es el crepúsculo, ahí donde su madre empieza. Heracles llega hasta ellas en el penúltimo de sus trabajos.",
  v:"Algunas fuentes las sitúan en el lejano norte y no en occidente, y hablan de un bosque entero en lugar de un solo árbol. Suelen contarse tres, pero el número oscila entre dos y siete; los nombres más frecuentes son Hesperaretusa o Hesperia, Eritia o Eritheis, y Egle, todos alusivos a la tarde, al rojo del atardecer y a la claridad del día. Hay tradiciones que las hacen hijas de Atlas en vez de la Noche."},
 {id:"momo", n:"Momo", rol:"Hijo de la Noche", epi:"La burla", gen:"gn", padres:["nix"],
  r:"La censura y el sarcasmo. No combate a nadie: se dedica a encontrarle el defecto a todo, incluso a las obras de los dioses, y por pasarse de mordaz terminó expulsado del Olimpo.",
  v:"Una tradición le atribuye haber sugerido a Zeus la guerra de Troya para aliviar a la Tierra del peso de tantos hombres."},
 {id:"cloto", n:"Cloto", rol:"Hija de la Noche", epi:"La Hilandera", gen:"gn", padres:["nix"],
  r:"La primera de las tres Moiras. Hila el hilo de la vida de cada individuo y lo saca de la rueca en el momento del nacimiento. Como sus hermanas, el arte la representa siempre como una mujer hermosa, mientras la literatura prefiere imaginarla anciana."},
 {id:"laquesis", n:"Láquesis", rol:"Hija de la Noche", epi:"La Repartidora", gen:"gn", padres:["nix"],
  r:"La segunda Moira: mide el hilo que su hermana ha hilado y asigna a cada uno el lote que le toca. Su nombre viene de la porción que se recibe por sorteo, y de ahí que el destino griego se parezca menos a un plan que a un reparto."},
 {id:"atropo", n:"Átropo", rol:"Hija de la Noche", epi:"La Inflexible", gen:"gn", padres:["nix"],
  r:"La tercera y más pequeña de las Moiras, y la que no admite vuelta atrás: corta el hilo con sus tijeras y esa vida termina. Su nombre significa literalmente la que no se deja desviar, ni por súplicas ni por ofrendas ni por los propios dioses."},
 {id:"hijos-eris", n:"Los hijos de Eris", rol:"Prole de la Discordia", epi:"Las fuerzas del conflicto", gen:"gn", padres:["eris"],
  r:"Trabajo, Olvido, Hambre, Penas, Luchas, Muertes, Homicidios, Peleas, Mentiras, Disputas y Desorden: las fuerzas dañinas que brotan de la discordia. Son alegorías antes que personajes, sin relatos propios ni culto, y Hesíodo las enumera de corrido para mostrar hasta dónde se ramifica un solo conflicto. Dos de esa lista sí tienen historia aparte: Ate y Horco."},
 {id:"ate", n:"Ate", rol:"Hija de la Discordia", epi:"La Ofuscación", gen:"gn", padres:["eris"],
  r:"No es el error sino la ceguera que lo precede: el momento en que un hombre pierde el juicio y se lanza a su propia ruina creyendo acertar. Camina sobre las cabezas de los hombres sin que sus pies toquen el suelo. Zeus mismo cayó en sus redes el día del nacimiento de Heracles y, furioso, la arrojó del Olimpo para siempre.",
  v:"Hesíodo la cuenta entre los hijos de Eris; Homero la hace hija de Zeus. En la Ilíada la siguen las Súplicas, cojas y arrugadas, que van detrás curando el daño que ella dejó."},
 {id:"horco", n:"Horco", rol:"Hijo de la Discordia", epi:"El Juramento", gen:"gn", padres:["eris"],
  r:"El juramento hecho castigo. No vela por la palabra dada sino por su quiebra: existe para caer sobre quien jura en falso a sabiendas. Hesíodo cuenta que las Erinias asistieron a su nacimiento, y advierte que el perjurio arruina el linaje entero del que lo comete, no solo al perjuro."},
 {id:"urano", n:"Urano", rol:"Primordial", epi:"El cielo estrellado", gen:"g1", padres:["gea"], pareja:["gea"],
  r:"El mayor de los dos hijos que Gea concibe sin padre, y el más importante: el cielo estrellado, unido después a ella. Encierra a sus hijos monstruosos en el vientre de la tierra y por eso cae bajo la hoz de Crono."},
 {id:"ponto", n:"Ponto", rol:"Primordial", epi:"El mar sin cultivar", gen:"g1", padres:["gea"], pareja:["gea"],
  r:"El mar profundo de olas agitadas, concebido por Gea sin padre como un rasgo de su propia superficie: el mar anterior a Poseidón, sin voluntad ni templos. Unido después a su propia madre engendra a Nereo, Forcis, Ceto, Taumante y Euribia, y con ellos una familia menor de dioses marinos, ninfas y criaturas monstruosas. Es la rama que nunca entra al Olimpo: de ella saldrán los seres que los héroes tendrán que enfrentar."},
 {id:"ourea", n:"Los Ourea", rol:"Primordial", epi:"Las Montañas", gen:"g1", padres:["gea"],
  r:"Las alturas del terreno, nacidas de Gea sin padre en el mismo impulso que Ponto. Son relieve antes que personajes: Hesíodo las nombra como morada grata a las ninfas y no vuelve a ocuparse de ellas, y a diferencia de sus hermanos no engendran linaje alguno. Los autores tardíos llegaron a contarlas y darles nombre monte por monte, empezando por el Olimpo."},
 {id:"erinias", n:"Las Erinias", rol:"Nacidas de la sangre", epi:"Las Vengadoras", gen:"g1", padres:["gea","urano"],
  r:"Gea queda encinta por unas gotas de la sangre de Urano, de modo que nacen ya del primer crimen contra un padre y a eso se dedican: persiguen sin descanso al que derrama sangre de su propia familia y al que rompe un juramento. No escuchan súplicas ni aceptan ofrendas. Son las que acosan a Orestes tras matar a su madre, hasta que un tribunal humano las desarma en Atenas.",
  v:"En la tradición arcaica no tienen nombres propios y su número es indeterminado; recién en época romana queda fijado que son tres y que se llaman Alecto, Tisífona y Megaira. Su filiación tampoco es única: el anexo sigue el nacimiento de la sangre de Urano derramada sobre Gea, pero Esquilo y otros autores, apoyándose en Hesíodo, las hacen hijas de la Noche, lo que encaja bien con su carácter, y Sófocles las presenta como hijas de la Tiniebla, Escoto, y de la Tierra. Fueron identificadas además con las Benévolas, Euménides, y las Venerables, Semnai: diosas de aspecto más amable y de nombre más propicio, porque nombrarlas por lo que son se consideraba peligroso."},
 {id:"gigantes", n:"Los Gigantes", rol:"Nacidos de la sangre", epi:"Los de brillante armadura", gen:"g1", padres:["gea","urano"],
  r:"Segunda progenie concebida de esa misma sangre: guerreros enormes y armados que Gea lanzará después contra los olímpicos. La Gigantomaquia solo puede ganarse con ayuda de un mortal, y ese mortal es Heracles. No deben confundirse con los titanes, que son la generación anterior y pierden otra guerra distinta."},
 {id:"melias", n:"Las Melias", rol:"Nacidas de la sangre", epi:"Las ninfas del fresno", gen:"g1", padres:["gea","urano"],
  r:"Tercera progenie de las gotas caídas sobre la tierra: las ninfas de los fresnos. De la madera de ese árbol se hacían las lanzas, de modo que del mismo derramamiento salen las vengadoras, los guerreros y la materia con que se mata. Una tradición hace nacer de ellas a la raza humana de bronce."},
 {id:"ciclopes", n:"Los Cíclopes", rol:"Primordial", epi:"Brontes, Estéropes y Arges", gen:"g1", padres:["gea","urano"],
  r:"Herreros de un solo ojo, encerrados dos veces y liberados por Zeus. Su agradecimiento cambia la historia: forjan el rayo, el tridente y el casco de invisibilidad."},
 {id:"hecatonquiros", n:"Los Hecatónquiros", rol:"Primordial", epi:"Los de cien brazos", gen:"g1", padres:["gea","urano"],
  r:"Coto, Briareo y Giges, con cincuenta cabezas cada uno. Deciden la Titanomaquia arrojando trescientas rocas a la vez y quedan de guardianes en el Tártaro."},

 {id:"forcis", n:"Forcis", rol:"Dios marino", epi:"El viejo del mar", gen:"gm", padres:["ponto","gea"], pareja:["ceto"],
  r:"Hijo de Ponto y Gea, y uno de los ancianos del mar anteriores a Poseidón. Unido a su hermana Ceto engendra la parte más temible de la rama marina: de los dos salen las Grayas, las Gorgonas y la serpiente que guarda las manzanas de oro. La Odisea nombra un puerto suyo en Ítaca, donde desembarca Odiseo."},
 {id:"ceto", n:"Ceto", rol:"Diosa marina", epi:"El monstruo del mar", gen:"gm", padres:["ponto","gea"], pareja:["forcis"],
  r:"Su nombre designa al gran monstruo marino, la ballena o el cetáceo devorador. Hermana y compañera de Forcis, es la madre de la progenie grotesca del mar: junto a él encabeza el linaje que quedará siempre al margen del Olimpo y que los héroes tendrán que enfrentar."},
 {id:"ladon", n:"Ladón", rol:"Monstruo", epi:"La serpiente del jardín", gen:"gm", padres:["forcis","ceto"],
  r:"Serpiente terrible nacida de Forcis y Ceto. Enroscado al árbol del jardín de los dioses, vigila las manzanas doradas junto a las Hespérides y no duerme jamás. Heracles lo mata, o lo burla, en el penúltimo de sus trabajos, y Hera lo sube al cielo convertido en la constelación del Dragón.",
  v:"Hesíodo lo presenta como hijo de Forcis y Ceto; Apolonio de Rodas lo hace nacer de la propia Gea. Algunas fuentes le atribuyen cien cabezas y todas las voces, y las hay que lo dejan solo dormido en vez de muerto."},
 {id:"crono", n:"Crono", rol:"Titán", epi:"El de mente retorcida", gen:"g2", padres:["gea","urano"], pareja:["rea"],
  r:"El menor y más audaz de los titanes. Derroca a su padre y gobierna la edad de oro, pero devora a sus hijos por miedo a repetir su propio crimen."},
 {id:"rea", n:"Rea", rol:"Titánide", epi:"La madre de los dioses", gen:"g2", padres:["gea","urano"], pareja:["crono"],
  r:"Esposa y hermana de Crono. Salva a Zeus escondiéndolo en Creta y entregando a su marido una piedra envuelta en pañales."},
 {id:"oceano", n:"Océano", rol:"Titán", epi:"El río que rodea el mundo", gen:"g2", padres:["gea","urano"], pareja:["tetis-t"],
  r:"El río que da la vuelta al disco de la tierra y del que procede toda agua. No participa en la guerra contra Zeus y conserva su dominio. Unido a su hermana Tetis engendra dos progenies de tres mil cada una: los ríos y las ninfas del Océano."},
 {id:"tetis-t", n:"Tetis", rol:"Titánide", epi:"Nodriza de las aguas", gen:"g2", padres:["gea","urano"], pareja:["oceano"],
  r:"Madre de todos los cursos de agua dulce y de las tres mil oceánides. Apenas actúa en los relatos: su papel es ser la fuente de la que todo lo que fluye desciende.",
  v:"No debe confundirse con Tetis la nereida, madre de Aquiles: son dos figuras distintas con nombre casi idéntico, Tethys y Thetis en griego."},
 {id:"potamoi", n:"Los Potamoi", rol:"Hijos de Océano", epi:"Los ríos del mundo", gen:"g3", padres:["oceano","tetis-t"],
  r:"Tres mil hijos varones, es decir, incontables: todos los ríos del mundo, que en griego son de género masculino. No son cursos de agua con un dios encima, sino el río mismo entendido como persona, y por eso pueden luchar. Los más nombrados son el Erídano, el Aqueloo, el Alfeo y el Escamandro.",
  v:"De los tres mil, la Teogonía nombra veinticinco, en este orden: Nilo, Alfeo, Erídano, Estrimón, Meandro, Istro, Fasis, Reso, Aqueloo, Neso, Rodio, Haliacmón, Heptáporo, Gránico, Esepo, Simoide, Peneo, Hermo, Ceco, Sangario, Ladón, Partenio, Eveno, Cares y Escamandro. Son ríos reales repartidos por todo el mundo conocido, desde Egipto hasta el Danubio, y varios de ellos —Esepo, Gránico, Simoide y Escamandro— riegan la llanura de Troya y reaparecen en la Ilíada. Ojo con el Ladón de esta lista, un río de Arcadia que no tiene relación con la serpiente del mismo nombre que guarda las manzanas de oro."},
 {id:"eridano", n:"Erídano", rol:"Río", epi:"El río del ámbar", gen:"g3", padres:["oceano","tetis-t"],
  r:"Río del lejano occidente, más imaginado que localizado: los griegos nunca se pusieron de acuerdo sobre cuál era. En sus aguas cae Faetón fulminado tras perder el control del carro del sol, y sus hermanas, convertidas en álamos en la orilla, lloran las lágrimas de ámbar que le dieron fama.",
  v:"Se lo ha identificado con el Po, con el Ródano y con ríos del Báltico, por la ruta del ámbar. También da nombre a una constelación, el río que corre a los pies de Orión."},
 {id:"aqueloo", n:"Aqueloo", rol:"Río", epi:"El mayor de los ríos", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río más grande de Grecia y el más venerado de todos los Potamoi: por él se juraba, y su nombre llegó a usarse para decir simplemente agua. Lucha con Heracles por la mano de Deyanira cambiando de forma —serpiente, toro— hasta que el héroe le arranca un cuerno. Ese cuerno roto se convierte en la cornucopia, el cuerno de la abundancia.",
  v:"Algunas fuentes lo hacen padre de las Sirenas, con una de las Musas."},
 {id:"alfeo", n:"Alfeo", rol:"Río", epi:"El río de Olimpia", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río que pasa junto al santuario de Olimpia, y uno de los dos que Heracles desvía para limpiar los establos de Augías en un solo día. Persigue a la ninfa Aretusa hasta Sicilia; ella es transformada en fuente y él se hunde bajo el mar para mezclar sus aguas con las de ella al otro lado."},
 {id:"escamandro", n:"Escamandro", rol:"Río", epi:"El río de Troya", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río que corre por la llanura de Troya. En la Ilíada se levanta contra Aquiles, harto de que atasque su cauce con cadáveres, y lo persigue con sus crecidas hasta que Hefesto lo hace retroceder con fuego: es la escena donde queda más claro que un río griego es una persona y no un paisaje.",
  v:"Homero dice que los dioses lo llaman Janto, el rubio, y los hombres Escamandro. Ese doble nombre, uno divino y otro humano, aparece varias veces en la Ilíada."},
 {id:"oceanides", n:"Las Oceánides", rol:"Hijas de Océano", epi:"Las ninfas del Océano", gen:"g3", padres:["oceano","tetis-t"],
  r:"Tres mil hijas, tantas como sus hermanos. Sus funciones no se limitan al agua: Hesíodo insiste en que están diseminadas por todas partes, tanto en la tierra como en las profundidades, y señala que cuidan en particular de los más jóvenes. De ellas salen figuras de primer orden como Metis, Clímene, Dione y Estigia. La mayoría de las muchachas que el Himno homérico a Deméter nombra como compañeras de Perséfone, y que estaban con ella recogiendo flores el día del rapto, figuran también en la lista de Hesíodo como oceánides.",
  v:"La Teogonía conserva el catálogo exacto de las cuarenta y una mayores: Acaste, Admete, Anfiro, Asia, Calipso, Calírroe, Cercéis, Clesidra, Clímene, Clitia, Criséis, Dione, Doris, Electra, Estigia, Eudora, Eurínome, Evágoras, Galaxaura, Hipo, Idía, Janto, Melóbosis, Menesto, Metis, Ociroe, Pasítoa, Peito, Petrea, Ploto, Plutón, Polidora, Primno, Rodía, Ródope, Telesto, Tique, Urania, Yanira, Yanta y Zeuxo. Muchos de esos nombres no son más que invenciones poéticas, igual que ocurre con las Nereidas, y algunos son transparentes: Asia da nombre al continente, Peito es la Persuasión, Plutón la Riqueza, Telesto el Éxito y Tique la Buena Fortuna. También se las llama Okeanidai u Okeaninai. Conviene no confundirlas con las Nereidas, ninfas del mar salado nacidas de Nereo, ni con las ninfas de fuentes y arroyos concretos, aunque las fuentes tardías mezclan los tres grupos."},
 {id:"hiperion", n:"Hiperión", rol:"Titán", epi:"El que va por lo alto", gen:"g2", padres:["gea","urano"], pareja:["tea"],
  r:"Titán de la luz celeste. Ni él ni su hermana Tea protagonizan mito alguno: su importancia está entera en los tres hijos que engendran juntos y que traen la luz a los cielos, Helios el Sol, Selene la Luna y Eos la Aurora. La épica homérica y los poemas arcaicos lo nombran sobre todo por eso, como el padre del dios sol. Antes de Apolo, la carrera del sol pertenece a su linaje y no al Olimpo.",
  v:"En Homero el nombre no siempre designa al titán: a veces funciona como epíteto del propio Helios, llamado Helios Hiperión, y a veces como patronímico, Hiperiónida, el hijo de Hiperión. Conviene comprobar en cada pasaje si se habla del padre o del hijo."},
 {id:"tea", n:"Tea", rol:"Titánide", epi:"La Divina", gen:"g2", padres:["gea","urano"], pareja:["hiperion"],
  r:"Su nombre significa simplemente divina. No aparece en ningún relato: su papel es ser la hermana y compañera de Hiperión y la madre de los tres astros. Se le atribuye la vista y el brillo del metal y las piedras preciosas, y los griegos creían que el oro reluce porque ella lo mira.",
  v:"Figuras como Tea y Febe, definidas casi por entero por su nombre y por con quién se unen, parecen inventadas para completar la lista de los doce. A Hesíodo o a algún predecesor suyo no le hacía falta mucha imaginación para producirlas."},
 {id:"ceo", n:"Ceo", rol:"Titán", epi:"El eje del cielo", gen:"g2", padres:["gea","urano"], pareja:["febe"],
  r:"Titán del pilar norte y del intelecto que interroga. Su lugar entre los titanes se explica sobre todo por su descendencia: unido a Febe engendra a Leto, y por ella es el abuelo de dos de las principales divinidades olímpicas, Apolo y Ártemis."},
 {id:"febe", n:"Febe", rol:"Titánide", epi:"La Radiante", gen:"g2", padres:["gea","urano"], pareja:["ceo"],
  r:"Su nombre significa radiante o brillante. Unida a Ceo es la madre de Leto, y fue dueña del oráculo de Delfos antes que Apolo, a quien se lo cede como regalo. De ella toma su nieto el epíteto Febo, que es el que más veces lo nombra en la Ilíada."},
 {id:"crio", n:"Crío", rol:"Titán", epi:"El carnero", gen:"g2", padres:["gea","urano"],
  r:"El más oscuro de los doce: su naturaleza y su origen son un misterio. Ni siquiera su nombre ayuda mucho, porque significa carnero y nadie sabe bien por qué. Solo se le conoce por su descendencia, que domina los vientos y los astros errantes.",
  v:"La asociación con la constelación de Aries y con el pilar sur del cielo es una conjetura tardía, construida a partir del nombre y no de ningún relato antiguo."},
 {id:"japeto", n:"Jápeto", rol:"Titán", epi:"El perforador", gen:"g2", padres:["gea","urano"],
  r:"Padre de Prometeo, Epimeteo y Atlas: la rama titánica que se juega el destino de los mortales. Los griegos lo tenían por antepasado de la humanidad."},
 {id:"temis", n:"Temis", rol:"Titánide", epi:"La ley que no se escribe", gen:"g2", padres:["gea","urano"], pareja:["zeus"],
  r:"Encarna el orden justo y la costumbre. Consejera de Zeus y madre de las Horas, es la única titánide sentada en el Olimpo.",
  v:"Hesíodo se contradice a sí mismo al atribuirle también las Moiras, que antes había hecho nacer de la Noche sola. El anexo sigue esa primera versión."},
 {id:"mnemosine", n:"Mnemósine", rol:"Titánide", epi:"La memoria", gen:"g2", padres:["gea","urano"], pareja:["zeus"],
  r:"Nueve noches con Zeus y nueve Musas: la poesía nace de la memoria, no de la inspiración súbita. Sin ella no habría relato del mito, porque antes de la escritura recordar y componer eran la misma tarea."},

 {id:"helios", n:"Helios", rol:"Titán menor", epi:"El sol", gen:"g3", padres:["hiperion","tea"],
  r:"Hijo de Hiperión y Tea. Cruza el cielo en un carro de cuatro caballos y lo ve todo: es quien delata a Afrodita ante Hefesto y a Hades ante Deméter. El robo de sus vacas en Trinacria, custodiadas por sus hijas, condena a los últimos compañeros de Odiseo. Ausente durante el reparto del mundo, se quedó con la isla de Rodas, que acababa de emerger del mar, y la tomó por esposa.",
  v:"La épica lo llama también Hiperión, por su padre, o Hiperiónida. Más tarde se lo confundirá con Apolo, aunque en las fuentes arcaicas son dioses distintos."},
 {id:"selene", n:"Selene", rol:"Titánide menor", epi:"La luna", gen:"g3", padres:["hiperion","tea"],
  r:"Conduce un carro de plata y ama al pastor Endimión, a quien Zeus concede un sueño eterno para que nunca envejezca."},
 {id:"eos", n:"Eos", rol:"Titánide menor", epi:"La de dedos de rosa", gen:"g3", padres:["hiperion","tea"],
  r:"Abre las puertas del cielo cada mañana. Pidió la inmortalidad para su amante Titono pero olvidó pedir la juventud, y él envejeció sin poder morir."},
 {id:"leto", n:"Leto", rol:"Titánide menor", epi:"La discreta", gen:"g3", padres:["ceo","febe"], pareja:["zeus"],
  r:"Perseguida por Hera, ninguna tierra firme se atreve a acogerla hasta que la isla flotante de Delos la recibe. Allí da a luz a los gemelos arqueros."},
 {id:"prometeo", n:"Prometeo", rol:"Titán menor", epi:"El que piensa antes", gen:"g3", padres:["japeto"],
  r:"Modela a los hombres con barro y les roba el fuego. Conoce el secreto que puede destronar a Zeus y por eso resiste treinta generaciones de tortura sin hablar."},
 {id:"epimeteo", n:"Epimeteo", rol:"Titán menor", epi:"El que piensa después", gen:"g3", padres:["japeto"],
  r:"Reparte todas las cualidades entre los animales y deja al hombre desnudo. Acepta a Pandora pese a la advertencia de su hermano."},
 {id:"atlas", n:"Atlas", rol:"Titán menor", epi:"El que sostiene", gen:"g3", padres:["japeto"],
  r:"Condenado a cargar la bóveda del cielo por su bando en la Titanomaquia. Solo se libra un instante, cuando Heracles se la sostiene para pedirle las manzanas de oro."},

 {id:"eurinome", n:"Eurínome", rol:"Oceánide", epi:"La de ancho dominio", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"De su unión con Zeus nacen las Gracias. Una tradición anterior la hace reina del Olimpo junto a Ofión antes de que Crono los derribara a ambos, de modo que habría gobernado el cielo antes que los titanes. Es también quien recoge a Hefesto en el fondo del mar cuando su madre lo arroja del Olimpo."},
 {id:"gracias", n:"Las Gracias", rol:"Hijas de Zeus", epi:"Las Cárites", gen:"g4", padres:["zeus","eurinome"],
  r:"Aglaya, Eufrósine y Talía: el esplendor, la alegría y la abundancia. Personifican todo lo que hace la vida grata y sin ellas ningún banquete, danza ni obra de arte sale bien. Acompañan habitualmente a Afrodita, y son ellas quienes la visten y perfuman."},
 {id:"peito", n:"Peito", rol:"Oceánide", epi:"La Persuasión", gen:"g3", padres:["oceano","tetis-t"],
  r:"Preside toda forma de persuasión, desde la política hasta la amatoria, y aparece a menudo como ayudante de Afrodita: es la que consigue el sí que la belleza sola no arranca. Los griegos le rendían culto, porque convencer a la asamblea y convencer a una persona les parecían la misma destreza.",
  v:"Hesíodo la cuenta entre las oceánides; otras fuentes la hacen hija de Afrodita o simple epíteto suyo, y en Roma se la identifica con Suada o Suadela."},
 {id:"tique", n:"Tique", rol:"Oceánide", epi:"La Fortuna", gen:"g3", padres:["oceano","tetis-t"],
  r:"Lo que a cada uno le toca sin que lo merezca ni lo pida: el azar, la suerte buena y la mala. Hesíodo apenas la nombra en la lista de las oceánides, pero con el tiempo crece hasta volverse una de las divinidades más veneradas del mundo griego, protectora de ciudades enteras, que la representaban coronada de murallas.",
  v:"Los romanos la identificaron con Fortuna. En época helenística se la asocia a Némesis como pareja de contrarios: una reparte al azar y la otra corrige lo desmedido."},
 {id:"dione", n:"Dione", rol:"Oceánide", epi:"La diosa, en femenino", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"Su nombre es la forma femenina del de Zeus, y a veces aparece como consorte suya: en Dodona, el santuario oracular más antiguo de Grecia, se le rendía culto junto a él en lugar de a Hera. En la Ilíada consuela a Afrodita cuando Diomedes la hiere en combate y la llama hija suya.",
  v:"Esa filiación es la clave de la versión homérica que hace a Afrodita hija de Zeus y Dione, en vez de nacida de la espuma. Hesíodo la cuenta entre las oceánides; otras listas la hacen titánide, hija de Gea y Urano."},
 {id:"calipso", n:"Calipso", rol:"Oceánide", epi:"La que oculta", gen:"g3", padres:["oceano","tetis-t"],
  r:"La ninfa de la isla de Ogigia, que retiene a Odiseo siete años y le ofrece la inmortalidad a cambio de quedarse. Él la rechaza por volver a casa, y ella lo deja marchar solo cuando Hermes se lo ordena de parte de Zeus. Su nombre significa la que esconde o encubre, y eso es exactamente lo que hace con el héroe: lo borra del mundo.",
  v:"Hesíodo la incluye en la lista de las oceánides; la Odisea, en cambio, la hace hija de Atlas."},
 {id:"doris", n:"Doris", rol:"Oceánide", epi:"La dadivosa", gen:"g3", padres:["oceano","tetis-t"], pareja:["nereo"],
  r:"Unida a Nereo, el viejo del mar, es la madre de las cincuenta Nereidas. Su nombre evoca el don o la abundancia que el mar entrega. Por ella la rama de Ponto y la de Océano quedan enlazadas: las ninfas del mar salado descienden a la vez de las dos familias que Gea fundó."},
 {id:"nereo", n:"Nereo", rol:"Dios marino", epi:"El viejo del mar", gen:"gm", padres:["ponto","gea"], pareja:["doris"],
  r:"El primogénito de Ponto y Gea, y el único benévolo de esa estirpe: justo, veraz y sin engaño. Conoce todas las cosas y cambia de forma para no responder, hasta que Heracles lo sujeta y lo obliga a revelar el camino hacia las manzanas de oro. Con Doris engendra a las cincuenta Nereidas."},
 {id:"nereidas", n:"Las Nereidas", rol:"Hijas de Nereo", epi:"Las ninfas del mar salado", gen:"gm", padres:["nereo","doris"],
  r:"Cincuenta ninfas que habitan el fondo del mar y acompañan a los navegantes. La más célebre es Tetis, la madre de Aquiles; también están Anfítrite, la reina del mar, y Galatea. Cuando Aquiles llora por Patroclo, todas suben juntas desde las profundidades a consolarlo.",
  v:"Como ocurre con las oceánides, buena parte de sus nombres son invenciones poéticas. No deben confundirse con las Oceánides, hijas de Océano y ninfas de las aguas en general."},
 {id:"anfitrite", n:"Anfítrite", rol:"Nereida", epi:"La reina del mar", gen:"gm", padres:["nereo","doris"], pareja:["poseidon"],
  r:"Unida a Poseidón es la reina del mar y la madre de Tritón. Al principio lo rechazó y huyó a esconderse en los confines del Océano; fue un delfín quien la encontró y la persuadió de volver, y en pago Poseidón lo puso entre las estrellas.",
  v:"La Teogonía la cuenta entre las nereidas, hija de Nereo y Doris, que es la filiación que sigue el anexo. Apolodoro, en cambio, la clasifica como oceánide, hija de Océano y Tetis."},
 {id:"climene", n:"Clímene", rol:"Oceánide", epi:"La de fama célebre", gen:"g3", padres:["oceano","tetis-t"], pareja:["japeto"],
  r:"Unida al titán Jápeto es la madre de Prometeo, Epimeteo, Atlas y Menecio, es decir, de la rama titánica que se juega el destino de los mortales. Una tradición la hace también madre de Faetón con Helios, el muchacho que quiso conducir el carro del sol y fue fulminado."},
 {id:"calirroe", n:"Calírroe", rol:"Oceánide", epi:"La de bella corriente", gen:"g3", padres:["oceano","tetis-t"],
  r:"Unida a Crisaor, el hijo que brotó del cuello de Medusa, es la madre de Gerión, el gigante de tres cuerpos cuyo ganado Heracles roba en el décimo de sus trabajos. Su descendencia la instala de lleno en la rama monstruosa, pese a ser hija de Océano."},
 {id:"perseida", n:"Perseida", rol:"Oceánide", epi:"La compañera de Helios", gen:"g3", padres:["oceano","tetis-t"], pareja:["helios"],
  r:"Unida a Helios es la madre de Circe, la hechicera de Eea, y de Eetes, rey de la Cólquide, además de Pasífae, la reina de Creta que concibe al Minotauro. De ella desciende por tanto casi toda la hechicería que aparece en los relatos griegos."},
 {id:"idia", n:"Idía", rol:"Oceánide", epi:"La que sabe", gen:"g3", padres:["oceano","tetis-t"],
  r:"Esposa de Eetes, el rey de la Cólquide que custodia el vellocino de oro, y madre de Medea. Su nombre alude al saber, lo que encaja con una hija que dominará la hechicería mejor que nadie y decidirá el éxito de los Argonautas."},
 {id:"estigia", n:"Estigia", rol:"Oceánide", epi:"La odiosa", gen:"g3", padres:["oceano","tetis-t"],
  r:"La diosa del río infernal que rodea el mundo de los muertos. Fue la primera en acudir con sus hijos al lado de Zeus en la guerra contra los titanes, y su recompensa fue que todo juramento divino se preste por sus aguas: el dios que jura en falso por Estigia queda un año sin aliento y nueve más apartado del Olimpo.",
  v:"Hesíodo la coloca al final de la lista de las oceánides, y esa posición indica que la tiene por la más importante de todas."},
 {id:"hestia", n:"Hestia", rol:"Olímpica", epi:"El hogar", gen:"g4", padres:["crono","rea"],
  r:"La primogénita devorada y la última en salir. Renuncia a su trono y a todo relato: su presencia es el fuego que no se deja apagar en la casa y en la ciudad."},
 {id:"demeter", n:"Deméter", rol:"Olímpica", epi:"La madre del grano", gen:"g4", padres:["crono","rea"], pareja:["zeus"],
  r:"Enseña la agricultura y controla la fertilidad de la tierra. Su duelo por Perséfone es la única vez que un dios doblega a otro por hambre."},
 {id:"hera", n:"Hera", rol:"Olímpica", epi:"Reina del Olimpo", gen:"g4", padres:["crono","rea"], pareja:["zeus"],
  r:"Diosa del matrimonio legítimo y esposa de un marido que jamás lo respeta. Su cólera persigue a las amantes y a los hijos bastardos, sobre todo a Heracles."},
 {id:"hades", n:"Hades", rol:"Olímpico", epi:"El de mucha riqueza", gen:"g4", padres:["crono","rea"], pareja:["persefone"],
  r:"Señor de los muertos, no dios de la maldad: es inflexible, no cruel. Casi nunca sube al Olimpo y su nombre se evita en voz alta."},
 {id:"poseidon", n:"Poseidón", rol:"Olímpico", epi:"El que sacude la tierra", gen:"g4", padres:["crono","rea"],
  r:"Manda en el mar, los caballos y los terremotos. Pierde el Ática ante Atenea y persigue a Odiseo por haber cegado a su hijo el cíclope."},
 {id:"zeus", n:"Zeus", rol:"Olímpico", epi:"Padre de dioses y hombres", gen:"g4", padres:["crono","rea"], pareja:["hera","demeter","leto","temis","mnemosine","alcmena","danae","leda","europa","semele","maya","metis"],
  r:"Guarda el rayo y el orden del mundo, incluido el juramento y la hospitalidad. Rompe el ciclo de padres derrocados tragando a Metis antes de que le dé un hijo más fuerte que él."},
 {id:"afrodita", n:"Afrodita", rol:"Olímpica", epi:"La nacida de la espuma", gen:"g4", padres:["urano"], pareja:["anquises"],
  r:"Crono arroja al mar los genitales de su padre y de la espuma que se arremolina en torno a ellos surge la diosa, que llega a tierra en Chipre. Nace por tanto de Urano y sin madre, y es más antigua que Zeus y que todos los olímpicos. Su poder no admite excepciones: solo Atenea, Ártemis y Hestia le resisten.",
  v:"Es la versión de Hesíodo, que explica su nombre por la espuma, afrós. Homero en cambio la hace hija de Zeus y de la oceánide Dione, sin nada que ver con la castración."},
 {id:"atenea", n:"Atenea", rol:"Olímpica", epi:"La de ojos de lechuza", gen:"g4", padres:["zeus","metis"],
  r:"Nace armada de la cabeza de Zeus. Es la guerra pensada frente a la carnicería de Ares, y patrona de los héroes que ganan con astucia: Perseo, Heracles, Odiseo."},
 {id:"apolo", n:"Apolo", rol:"Olímpico", epi:"El del arco de plata", gen:"g4", padres:["zeus","leto"],
  r:"Oráculo, música, medicina y peste: cura y mata con la misma flecha. Su templo en Delfos ordena conocerse a uno mismo y no pasarse de la raya."},
 {id:"artemisa", n:"Ártemis", rol:"Olímpica", epi:"La cazadora", gen:"g4", padres:["zeus","leto"],
  r:"Gemela de Apolo y virgen por elección. Protege a las crías y a las jóvenes, y castiga sin apelación a quien invade su bosque: Acteón terminó devorado por sus perros."},
 {id:"ares", n:"Ares", rol:"Olímpico", epi:"El azote de los hombres", gen:"g4", padres:["zeus","hera"], pareja:["afrodita"],
  r:"La guerra como matanza y pánico, sin gloria. Ni su padre lo quiere, y en la Ilíada Atenea lo derriba de un pedrada."},
 {id:"hefesto", n:"Hefesto", rol:"Olímpico", epi:"El herrero cojo", gen:"g4", padres:["hera"], pareja:["afrodita"],
  r:"Único dios que trabaja. Concebido por Hera sin varón y arrojado del Olimpo, se venga con obras maestras: las armas de Aquiles, los autómatas de oro, la red que atrapa a los amantes."},
 {id:"hermes", n:"Hermes", rol:"Olímpico", epi:"El de las sandalias aladas", gen:"g4", padres:["zeus","maya"],
  r:"Mensajero, ladrón, guía de los muertos y patrón de los caminos. El día que nació ya había robado el ganado de Apolo e inventado la lira para pagarle."},
 {id:"dioniso", n:"Dioniso", rol:"Olímpico", epi:"El nacido dos veces", gen:"g4", padres:["zeus","semele"],
  r:"Rescatado del vientre de su madre fulminada y cosido al muslo de Zeus. Lo cría su tía Ino tras la muerte de Sémele. Trae el vino, el éxtasis y el teatro, y destruye a quien niega su divinidad: su propio primo Penteo muere despedazado por negarle culto en Tebas."},
 {id:"persefone", n:"Perséfone", rol:"Olímpica", epi:"Reina del inframundo", gen:"g4", padres:["zeus","demeter"], pareja:["hades"],
  r:"Muchacha raptada y soberana temible a la vez. Los granos de granada que come la atan al mundo de abajo y reparten el año entre su madre y su esposo."},
 {id:"metis", n:"Metis", rol:"Oceánide", epi:"La astucia", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"Oceánide, primera esposa de Zeus y quien le dio la pócima que hizo vomitar a Crono. Él la traga estando embarazada, y así la inteligencia queda dentro del poder."},
 {id:"maya", n:"Maya", rol:"Pléyade", epi:"La mayor de las Pléyades", gen:"g4", padres:["atlas"], pareja:["zeus"],
  r:"Hija de Atlas, vive apartada en una cueva de Arcadia. Madre de Hermes, a quien encuentra fuera de la cuna la misma noche en que lo dio a luz."},
 {id:"semele", n:"Sémele", rol:"Princesa tebana", epi:"La fulminada", gen:"gt", padres:["cadmo","harmonia"], pareja:["zeus"],
  r:"Hija de Cadmo y Harmonía, y por tanto nieta de dioses por un lado y de reyes fenicios por el otro. Amante secreta de Zeus, es engañada por Hera para que le pida mostrarse en su forma verdadera, y el resplandor la calcina estando encinta. Zeus rescata al feto y lo cose a su muslo hasta que nace; años después, ya dios, Dioniso baja al Hades a buscarla y la hace inmortal."},

 {id:"io", n:"Ío", rol:"Princesa de Argos", epi:"La vaca errante", gen:"gt", padres:[], pareja:["zeus"],
  r:"Sacerdotisa amada por Zeus y transformada en vaca para ocultarla de Hera, que igual la descubre y le envía un tábano para que no descanse jamás. Su huida la lleva cruzando medio mundo —el Bósforo, el paso de la vaca, se llama así por ella— hasta Egipto, donde recobra la forma humana. Sus descendientes se dispersan por el Mediterráneo y de uno de ellos sale la casa de Fenicia."},
 {id:"epafo", n:"Épafo", rol:"Rey de Egipto", epi:"El del roce", gen:"gt", padres:["zeus","io"],
  r:"Hijo que Ío concibe en Egipto por el solo roce de la mano de Zeus, de donde le viene el nombre. Funda Menfis y encabeza la rama africana del linaje."},
 {id:"libia", n:"Libia", rol:"Reina", epi:"La que da nombre a África", gen:"gt", padres:["epafo"], pareja:["poseidon"],
  r:"Hija de Épafo y nieta de Ío, dio su nombre a toda la tierra que los griegos conocían al oeste de Egipto. De su unión con Poseidón nacen Agenor, que reinará en Fenicia, y Belo, que se queda en Egipto: en ella se separan las dos ramas del linaje.",
  v:"Varias fuentes acortan la cadena y llaman a Europa nieta de Ío sin mencionar a Épafo ni a Libia."},
 {id:"agenor", n:"Agenor", rol:"Rey de Tiro", epi:"El fenicio", gen:"gt", padres:["poseidon","libia"], pareja:["telefasa"],
  r:"Rey de Tiro y padre de Europa y Cadmo. Cuando Zeus rapta a su hija en forma de toro, manda a sus hijos a buscarla con la orden de no volver sin ella: ninguno regresa, y de esa búsqueda sin retorno nacen varias ciudades griegas."},
 {id:"telefasa", n:"Telefasa", rol:"Reina de Tiro", epi:"La madre que buscó", gen:"gt", padres:[], pareja:["agenor"],
  r:"Esposa de Agenor y madre de Cadmo y Europa. Acompaña a su hijo en la búsqueda de la hija raptada y muere en Tracia sin haberla encontrado.",
  v:"Algunas fuentes la llaman Argíope."},
 {id:"cadmo", n:"Cadmo", rol:"Rey de Tebas", epi:"El fundador", gen:"gt", padres:["agenor","telefasa"], pareja:["harmonia"],
  r:"Hermano de Europa y descendiente de Ío. Enviado a buscar a su hermana, el oráculo de Delfos le manda seguir a una vaca y fundar una ciudad donde ella se eche: así nace Tebas. Mata al dragón que guardaba la fuente y siembra sus dientes, de los que brotan guerreros armados. La tradición le atribuye haber traído el alfabeto a Grecia.",
  v:"Él y Harmonía terminan sus días convertidos en serpientes, castigo o consuelo según la versión que se siga."},
 {id:"harmonia", n:"Harmonía", rol:"Diosa", epi:"La concordia", gen:"gt", padres:["ares","afrodita"], pareja:["cadmo"],
  r:"Hija de Ares y Afrodita, la guerra y el amor: su nombre es el acuerdo que nace de esa mezcla. Su boda con Cadmo es la primera a la que asisten todos los dioses. El collar que recibe de regalo, obra de Hefesto, trae la desgracia a cuantas mujeres lo llevan después y arrastra a la casa tebana durante generaciones."},
 {id:"ino", n:"Ino", rol:"Princesa tebana", epi:"Leucótea, la diosa blanca", gen:"gt", padres:["cadmo","harmonia"],
  r:"Reina de Orcómeno y la que cría a Dioniso tras la muerte de su hermana Sémele. Enloquecida por Hera como castigo, se arroja al mar con su hijo y allí es transformada en la diosa marina Leucótea. En la Odisea es ella quien socorre a Odiseo náufrago y le entrega el velo que lo mantiene a flote."},
 {id:"agave", n:"Ágave", rol:"Princesa tebana", epi:"La que no reconoció", gen:"gt", padres:["cadmo","harmonia"],
  r:"Madre de Penteo, el rey que niega la divinidad de su primo Dioniso y prohíbe su culto. En el delirio báquico que el dios provoca, Ágave despedaza a su propio hijo creyendo cazar un león, y solo al bajar del monte con la cabeza en las manos comprende lo que ha hecho."},
 {id:"autonoe", n:"Autónoe", rol:"Princesa tebana", epi:"La madre de Acteón", gen:"gt", padres:["cadmo","harmonia"],
  r:"Madre de Acteón, el cazador que sorprende a Ártemis desnuda en el baño y es convertido en ciervo y devorado por sus propios perros. Como sus hermanas, su destino es sobrevivir a un hijo muerto por ofender a una divinidad."},
 {id:"polidoro", n:"Polidoro", rol:"Rey de Tebas", epi:"El heredero", gen:"gt", padres:["cadmo","harmonia"],
  r:"Único varón de la primera camada y sucesor de Cadmo en el trono de Tebas. Su línea continúa hasta Layo y, por él, hasta Edipo: la maldición de la casa tebana desciende por esta rama."},
 {id:"ilirio", n:"Ilirio", rol:"Príncipe", epi:"El nacido tarde", gen:"gt", padres:["cadmo","harmonia"],
  r:"Hijo tardío de Cadmo y Harmonía, nacido cuando ambos ya habían dejado Tebas. Da nombre a los ilirios, el pueblo del Adriático, de modo que cierra el arco de la familia: empieza en Fenicia y termina en los Balcanes."},
 {id:"radamantis", n:"Radamantis", rol:"Juez de los muertos", epi:"El justo", gen:"gt", padres:["zeus","europa"],
  r:"Hermano de Minos y legislador de fama intachable: sus leyes eran tan justas que los griegos decían que ni él mismo podía torcerlas. Vivió larguísimamente y acompañó a su madre hasta la muerte de ella. Tras morir juzga también a las almas, y le toca el turno de los que llegan desde Asia."},
 {id:"sarpedon", n:"Sarpedón", rol:"Príncipe cretense", epi:"El desterrado", gen:"gt", padres:["zeus","europa"],
  r:"El tercero de los hijos de Europa. Expulsado de Creta por su hermano Minos, se marcha a Licia y allí reina. Su destino queda difuso en las fuentes y se diluye entre otras figuras del mismo nombre.",
  v:"No debe confundirse con el Sarpedón que muere ante Troya a manos de Patroclo, aunque los antiguos ya los mezclaban: algunos hacen al segundo nieto del primero para salvar la distancia de generaciones."},
 {id:"asterion", n:"Asterión", rol:"Rey de Creta", epi:"El padre adoptivo", gen:"gt", padres:[], pareja:["europa"],
  r:"Rey de Creta que se casa con Europa tras el rapto y cría como propios a los tres hijos que ella tuvo con Zeus. Por él quedó en Gortina el culto a Zeus Asterio, y su nombre reaparece luego como el del Minotauro."},
 {id:"ariadna", n:"Ariadna", rol:"Princesa cretense", epi:"La del hilo", gen:"gt", padres:["minos"], pareja:["dioniso"],
  r:"Hija de Minos, da a Teseo el ovillo que le permite salir del laberinto y huye con él, que la abandona dormida en la isla de Naxos. Allí la encuentra Dioniso y la toma por esposa; la corona que le regala queda en el cielo como la constelación de la Corona Boreal."},
 {id:"enopion", n:"Enopión", rol:"Rey de Quíos", epi:"El del vino", gen:"g5", padres:["dioniso","ariadna"],
  r:"Su nombre significa bebedor de vino, y es él quien enseña a hacerlo en la isla de Quíos. Ciega a Orión por acercarse a su hija, y el gigante debe caminar hacia el sol naciente para recuperar la vista."},
 {id:"estafilo", n:"Estáfilo", rol:"Argonauta", epi:"El racimo de uva", gen:"g5", padres:["dioniso","ariadna"],
  r:"Personificación del racimo, como su hermano lo es del vino. Figura entre los Argonautas que acompañan a Jasón en busca del vellocino de oro."},
 {id:"toante", n:"Toante", rol:"Rey de Lemnos", epi:"El salvado por su hija", gen:"g5", padres:["dioniso","ariadna"],
  r:"Rey de Lemnos. Cuando las mujeres de la isla asesinan a todos sus hombres, su hija Hipsípila lo esconde y lo salva, único varón sobreviviente de aquella matanza."},
 {id:"abante", n:"Abante", rol:"Rey de Argos", epi:"El del escudo", gen:"ga", padres:[],
  r:"Rey de Argos y padre de Acrisio. Su escudo tenía fama de ahuyentar por sí solo a los enemigos, y de él desciende la línea real argiva que desemboca en Perseo."},
 {id:"acrisio", n:"Acrisio", rol:"Rey de Argos", epi:"El que huyó del oráculo", gen:"ga", padres:["abante"], pareja:["euridice-a"],
  r:"Encierra a su hija Dánae para que no tenga descendencia, porque un oráculo le anunció que moriría a manos de su nieto. Todo lo que hace por evitarlo lo acerca al final anunciado: años después, un disco lanzado por Perseo en unos juegos lo alcanza por accidente y lo mata."},
 {id:"euridice-a", n:"Eurídice", rol:"Reina de Argos", epi:"La madre de Dánae", gen:"ga", padres:["lacedemon"], pareja:["acrisio"],
  r:"Esposa de Acrisio y madre de Dánae. Por ella la casa de Argos se emparenta con la de Esparta, ya que es hija de Lacedemón, el fundador de esa ciudad.",
  v:"Algunas fuentes secundarias la llaman Aganipe. No debe confundirse con la Eurídice esposa de Orfeo, que es otra figura."},
 {id:"lacedemon", n:"Lacedemón", rol:"Rey de Esparta", epi:"El fundador", gen:"ga", padres:[],
  r:"Fundador de Esparta, a la que dio su propio nombre: Lacedemonia. Abuelo materno de Dánae y, por tanto, bisabuelo de Perseo."},
 {id:"perseo", n:"Perseo", rol:"Héroe", epi:"El matador de Medusa", gen:"ga", padres:["zeus","danae"], pareja:["andromeda"],
  r:"Concebido en una lluvia de oro dentro de una cámara cerrada. Es el primer héroe de la estirpe de Zeus y, por su unión con Andrómeda, el bisabuelo de Heracles: casi todos los linajes heroicos pasan por él."},
 {id:"andromeda", n:"Andrómeda", rol:"Princesa de Etiopía", epi:"La encadenada", gen:"ga", padres:[], pareja:["perseo"],
  r:"Encadenada a una roca como ofrenda a un monstruo marino, por la vanidad de su madre, que se jactó de ser más bella que las nereidas. Perseo la libera y la toma por esposa. De los dos desciende la casa de Micenas y, por ella, Heracles.",
  v:"Ella, Perseo y sus padres Cefeo y Casiopea fueron puestos entre las estrellas: todavía son constelaciones vecinas en el cielo del norte."},
 {id:"electrion", n:"Electrión", rol:"Rey de Micenas", epi:"El suegro de Anfitrión", gen:"ga", padres:["perseo","andromeda"], pareja:["anaxo"],
  r:"Hijo de Perseo y Andrómeda y rey de Tirinto y Micenas. Muere a manos de su propio yerno Anfitrión, en un accidente con una maza que rebota, y esa muerte involuntaria obliga a la pareja a exiliarse a Tebas: por eso Heracles nace lejos del reino que le correspondía."},
 {id:"anaxo", n:"Anaxo", rol:"Princesa de Micenas", epi:"La madre de Alcmena", gen:"ga", padres:[], pareja:["electrion"],
  r:"Esposa de Electrión y madre de Alcmena. Su papel en el relato es enteramente genealógico: sostiene el enlace entre la casa de Perseo y el nacimiento de Heracles.",
  v:"Otras versiones dan como madre de Alcmena a Lisídice o a Eurídice, nombres que circulan en la misma rama."},
 {id:"anfitrion", n:"Anfitrión", rol:"Príncipe de Tirinto", epi:"El esposo suplantado", gen:"ga", padres:[], pareja:["alcmena"],
  r:"Primo y marido de Alcmena. Mata sin querer a su suegro Electrión y debe exiliarse con ella a Tebas. Mientras está en campaña, Zeus toma su forma y ocupa su lugar una noche; al volver, engendra a Ificles. Cría como propio a Heracles, el hijo del dios."},
 {id:"ificles", n:"Ificles", rol:"Héroe", epi:"El mellizo mortal", gen:"ga", padres:["anfitrion","alcmena"],
  r:"Nacido la misma noche que Heracles pero de padre humano, y esa diferencia lo define: cuando Hera manda las serpientes a la cuna, Heracles las estrangula e Ificles grita de terror. Acompaña después a su hermano en varias campañas y muere en una de ellas."},
 {id:"laonome", n:"Laónome", rol:"Princesa", epi:"La hermana de Heracles", gen:"ga", padres:["anfitrion","alcmena"],
  r:"Hija de Anfitrión y Alcmena, y por tanto hermana mortal de Heracles. Apenas aparece en los relatos: se la nombra sobre todo para enlazar la casa de Tebas con la de los argonautas por su matrimonio."},
 {id:"danae", n:"Dánae", rol:"Princesa de Argos", epi:"La encerrada", gen:"ga", padres:["acrisio","euridice-a"], pareja:["zeus"],
  r:"Hija de Acrisio y Eurídice. Advertido por un oráculo de que el hijo de su hija lo matará, su padre la encierra en una cámara subterránea de bronce; Zeus se cuela en forma de lluvia de oro y así concibe a Perseo. Madre e hijo son echados al mar en un arca de madera y sobreviven al llegar a la isla de Sérifos."},
 {id:"heracles", n:"Heracles", rol:"Héroe", epi:"La gloria de Hera", gen:"ga", padres:["zeus","alcmena"],
  r:"El más fuerte y el más castigado. Sus doce trabajos limpian el mundo de monstruos, y tras morir por la túnica envenenada de Neso es el único mortal admitido entre los dioses."},
 {id:"alcmena", n:"Alcmena", rol:"Princesa de Micenas", epi:"La de la noche triple", gen:"ga", padres:["electrion","anaxo"], pareja:["zeus","anfitrion"],
  r:"Hija de Electrión y nieta de Perseo y Andrómeda. Casada con su primo Anfitrión, Zeus la visita tomando la forma exacta de su marido y alarga aquella noche al triple. De esa doble unión nacen mellizos de padres distintos: Heracles, hijo del dios, e Ificles, hijo del esposo."},
 {id:"helena", n:"Helena", rol:"Semidiosa", epi:"La de Esparta", gen:"ge", padres:["zeus","leda"],
  r:"Nacida del huevo que puso su madre tras la visita de Zeus en forma de cisne. La mujer más bella del mundo y el premio que Afrodita promete a Paris: su fuga con él desata la guerra de Troya.",
  v:"Una versión sostiene que ella nunca llegó a Troya y que allí solo viajó un fantasma suyo, mientras la verdadera esperaba en Egipto."},
 {id:"leda", n:"Leda", rol:"Reina de Esparta", epi:"La del cisne", gen:"ge", padres:[], pareja:["zeus","tindareo"],
  r:"Zeus se une a ella en forma de cisne junto al río Eurotas, y esa misma noche se acuesta también con su marido Tindáreo. Pone un huevo del que salen cuatro hijos de dos padres distintos: Helena y Pólux, del dios; Clitemnestra y Cástor, del rey.",
  v:"Las versiones difieren en el reparto. Algunas hacen a los cuatro hijos de Zeus, con Clitemnestra y Helena saliendo de un segundo huevo; otras dejan solo a Helena como hija del dios y atribuyen a Tindáreo tanto a Cástor como a Pólux. Hay además una tradición que la deifica después como Némesis, y otra en que es la propia Némesis quien pone el huevo y Leda solo lo cría."},
 {id:"tindareo", n:"Tindáreo", rol:"Rey de Esparta", epi:"El esposo de Leda", gen:"ge", padres:[], pareja:["leda"],
  r:"Rey de Esparta y marido de Leda. Ante la multitud de pretendientes que reclama a Helena, los obliga a todos a jurar que defenderán al elegido contra quien intente arrebatársela: ese juramento es lo que después convierte un rapto privado en una guerra de toda Grecia."},
 {id:"clitemnestra", n:"Clitemnestra", rol:"Reina de Micenas", epi:"La que esperó diez años", gen:"ge", padres:["tindareo","leda"],
  r:"Hermana de Helena y esposa de Agamenón. Cuando su marido sacrifica a su hija Ifigenia para lograr viento favorable hacia Troya, ella pasa la guerra entera preparando la respuesta: al regreso lo asesina en el baño. Su propio hijo Orestes la matará a su vez para vengar al padre."},
 {id:"castor", n:"Cástor", rol:"Dioscuro", epi:"El domador de caballos", gen:"ge", padres:["tindareo","leda"],
  r:"El mellizo mortal, hijo de Tindáreo y maestro en el manejo de caballos. Muere en una reyerta por un robo de ganado, y su hermano se niega a sobrevivirle."},
 {id:"polux", n:"Pólux", rol:"Dioscuro", epi:"El púgil inmortal", gen:"ge", padres:["zeus","leda"],
  r:"El mellizo inmortal, hijo de Zeus y campeón en el pugilato. Al morir Cástor pide compartir con él su inmortalidad, y Zeus se la concede a medias: pasan alternadamente un día entre los dioses y otro entre los muertos. Los dos juntos forman la constelación de Géminis y acuden en auxilio de los navegantes en la tormenta.",
  v:"Como pareja se los llama los Dioscuros, los muchachos de Zeus, aunque en rigor solo uno lo sea. En Roma son Cástor y Pólux, con templo propio en el Foro."},
 {id:"minos", n:"Minos", rol:"Rey de Creta", epi:"El juez de los muertos", gen:"gt", padres:["zeus","europa"],
  r:"Rey de Creta y dueño del laberinto, criado por Asterión junto a sus hermanos. Oculta allí al Minotauro nacido del castigo de Poseidón y, tras morir, juzga a las almas en el inframundo. De su nombre viene el de la cultura minoica."},
 {id:"europa", n:"Europa", rol:"Princesa fenicia", epi:"La raptada por el toro", gen:"gt", padres:["agenor","telefasa"], pareja:["zeus","asterion"],
  r:"Jugaba con sus amigas en la playa cuando Zeus, prendado de ella, se le acercó convertido en un toro manso; ella se apartó del grupo atraída por el animal y, al subirse a su lomo, el toro echó a correr hacia el mar. Ovidio la describe vuelta hacia la orilla, agarrada con la mano derecha a un cuerno. La llevó desde Levante hasta Creta, y de sus amores en Gortina nacieron Minos, Radamantis y Sarpedón. Su nombre terminó designando un continente entero.",
  v:"En Gortina se rindió culto a Europa junto a Zeus Asterio, epíteto tomado de Asterión, el rey cretense con quien ella se casó después."},
 {id:"teseo", n:"Teseo", rol:"Héroe", epi:"El sinoicista de Atenas", gen:"g5", padres:["poseidon"],
  r:"Hijo de un padre doble, Egeo y Poseidón. Mata al Minotauro, unifica el Ática y encarna al héroe convertido en rey y legislador."},
 {id:"aquiles", n:"Aquiles", rol:"Héroe", epi:"El de los pies ligeros", gen:"gf", padres:["peleo","tetis-n"], pareja:["deidamia"],
  r:"Hijo del rey mortal Peleo y de la nereida Tetis, que lo sumerge en la laguna Estigia sujetándolo por el talón y así lo deja invulnerable salvo en ese punto. Elige a sabiendas la vida corta con gloria eterna sobre la larga y olvidada. Su cólera contra Agamenón es el asunto con que se abre la Ilíada.",
  v:"Se lo nombra a menudo por su ascendencia: Pélida, el hijo de Peleo, y Eácida, el descendiente de Éaco. Por esa línea paterna desciende directamente de Zeus."},
 {id:"eaco", n:"Éaco", rol:"Rey de Egina", epi:"El tercer juez", gen:"gf", padres:["zeus"], pareja:["endeis"],
  r:"Hijo de Zeus y rey de Egina. Tuvo fama de ser el más piadoso de los mortales, y cuando una peste despobló su isla pidió a su padre que convirtiera en hombres a las hormigas de un roble: así nacieron los mirmidones. Tras morir se sienta junto a Minos y Radamantis a juzgar a las almas, y le toca el turno de los europeos."},
 {id:"endeis", n:"Endeide", rol:"Reina de Egina", epi:"La madre de Peleo", gen:"gf", padres:[], pareja:["eaco"],
  r:"Esposa de Éaco y madre de Peleo y Telamón. Su rivalidad con la otra mujer de Éaco empuja a sus hijos a matar al medio hermano, crimen que les cuesta el destierro de Egina y lleva a Peleo hasta Ftía.",
  v:"También aparece transcrita como Endeís o Endeïs."},
 {id:"peleo", n:"Peleo", rol:"Rey de Ftía", epi:"El que ganó a una diosa", gen:"gf", padres:["eaco","endeis"], pareja:["tetis-n"],
  r:"Desterrado de Egina, termina reinando en Ftía sobre los mirmidones. Para desposar a Tetis debe sujetarla mientras ella se transforma en fuego, agua, león y serpiente, hasta que se rinde. A sus bodas asisten todos los dioses, y de ese banquete sale la manzana que desata la guerra de Troya."},
 {id:"tetis-n", n:"Tetis", rol:"Nereida", epi:"La de pies de plata", gen:"gm", padres:["nereo","doris"], pareja:["peleo"],
  r:"La más célebre de las nereidas. Un oráculo advirtió que su hijo sería más grande que el padre, y por eso Zeus y Poseidón renunciaron a ella y la casaron con un mortal. Intercede sin descanso por Aquiles ante los dioses y sabe desde el principio que va a sobrevivirlo.",
  v:"No debe confundirse con la titánide Tetis, esposa de Océano: en griego son Thetis y Tethys, dos figuras distintas."},
 {id:"deidamia", n:"Deidamía", rol:"Princesa de Esciros", epi:"La de Esciros", gen:"gf", padres:[], pareja:["aquiles"],
  r:"Princesa en cuya corte Tetis esconde a Aquiles vestido de muchacha para librarlo de la guerra. De esa estancia nace Neoptólemo, poco antes de que Odiseo descubra al héroe y se lo lleve a Troya."},
 {id:"neoptolemo", n:"Neoptólemo", rol:"Héroe", epi:"Pirro, el de la guerra nueva", gen:"gf", padres:["aquiles","deidamia"],
  r:"Traído a Troya cuando ya había muerto su padre, porque un oráculo dijo que la ciudad no caería sin él. Participa en la última fase de la guerra y en el saqueo, con una violencia que a los propios griegos les pareció excesiva.",
  v:"La tradición hace descender de él a los reyes de Epiro, y por esa línea a la familia de Olimpia, la madre de Alejandro Magno."},
 {id:"eneas", n:"Eneas", rol:"Héroe", epi:"El piadoso", gen:"g5", padres:["afrodita","anquises"],
  r:"Escapa de Troya en llamas cargando a su padre y llevando de la mano a su hijo. Su viaje hacia occidente convierte el final griego en el comienzo de Roma."},
 {id:"anquises", n:"Anquises", rol:"Mortal", epi:"El pastor del Ida", gen:"g5", padres:[], pareja:["afrodita"],
  r:"Amado por Afrodita y advertido de no jactarse jamás de ello. Habló, y quedó lisiado; su hijo tendría que sacarlo a hombros de la ciudad en ruinas."},
 {id:"musas", n:"Las Musas", rol:"Hijas de Zeus", epi:"Las nueve", gen:"g4", padres:["zeus","mnemosine"],
  r:"Nueve hermanas nacidas en nueve noches seguidas, cada una dueña de un arte: Calíope la épica, Clío la historia, Erato la lírica amorosa, Euterpe la música de flauta, Melpómene la tragedia, Polimnia los himnos, Talía la comedia, Terpsícore la danza y Urania la astronomía. A ellas invoca el poeta al empezar, porque sin memoria no hay relato."},
 {id:"caliope", n:"Calíope", rol:"Musa", epi:"La de bella voz", gen:"g4", padres:["zeus","mnemosine"], pareja:["eagro"],
  r:"La mayor de las Musas y la de la poesía épica y la elocuencia: es la que inspira los poemas largos, los que cuentan guerras y regresos. Madre de Orfeo, a quien lega la voz que lo hace capaz de conmover hasta a los muertos."},
 {id:"eagro", n:"Eagro", rol:"Rey de Tracia", epi:"El tracio", gen:"g5", padres:[], pareja:["caliope"],
  r:"Rey de Tracia y padre de Orfeo en la versión más extendida. Su reino, en el norte del mundo griego, explica que a su hijo se lo tenga por venido de los márgenes y no de las ciudades centrales."},
 {id:"euridice-o", n:"Eurídice", rol:"Ninfa", epi:"La esposa de Orfeo", gen:"g5", padres:[], pareja:["orfeo"],
  r:"Ninfa que muere el día de su boda, mordida por una serpiente mientras huía por un prado. Su muerte es lo que empuja a Orfeo al descenso, y su segunda pérdida, a un paso de la salida, es el corazón del mito.",
  v:"No debe confundirse con la Eurídice reina de Argos, madre de Dánae."},
 {id:"lino", n:"Lino", rol:"Músico", epi:"El del ritmo", gen:"g5", padres:["eagro","caliope"],
  r:"Hermano de Orfeo, a quien se atribuye la invención del ritmo y la melodía. Fue maestro de música de Heracles y murió a manos de su propio alumno, que le partió la lira en la cabeza al ser reprendido.",
  v:"Su nombre designaba también un canto de lamento, el linos, que se entonaba en la vendimia y en los funerales."},
 {id:"yalimo", n:"Yálimo", rol:"Personificación", epi:"El lamento", gen:"g5", padres:["eagro","caliope"],
  r:"Hermano de Orfeo y de Lino, y personificación del canto fúnebre. Como su hermano, es a la vez una figura y un género: el ialemo era el lamento que se cantaba por los muertos."},
 {id:"himeneo", n:"Himeneo", rol:"Dios del matrimonio", epi:"El canto de bodas", gen:"g5", padres:["eagro","caliope"],
  r:"Hermano de Orfeo y dios del canto nupcial: su nombre se gritaba en las bodas griegas para invocar buena fortuna. Una tradición cuenta que desapareció la noche misma de su boda, y que por eso se lo llama en todas las demás.",
  v:"Su filiación varía mucho: se lo hace hijo de Apolo y de otras Musas según la fuente."},
 {id:"rodas", n:"Rodas", rol:"Ninfa", epi:"La isla emergida", gen:"gm", padres:["poseidon","anfitrite"], pareja:["helios"],
  r:"Ninfa epónima de la isla de Rodas. Cuando los dioses se repartieron la tierra, Helios estaba ausente cumpliendo su carrera y quedó sin lote; pidió entonces quedarse con una tierra nueva y maravillosa que había visto emerger del mar mientras se levantaba sobre las aguas. Esa isla era ella, y la tomó por esposa.",
  v:"Su filiación varía: además de hija de Poseidón y Anfítrite, se la hace hija de Afrodita o de la ninfa Halia."},
 {id:"heliadas", n:"Los Helíadas", rol:"Hijos de Helios", epi:"Los siete de Rodas", gen:"g5", padres:["helios","rodas"],
  r:"Siete hijos de Helios y Rodas, los primeros habitantes de la isla y los mejores astrónomos y navegantes de su tiempo, porque heredaron del padre la costumbre de mirar el cielo. La envidia rompió el grupo: varios mataron al hermano más dotado y tuvieron que huir de la isla.",
  v:"No deben confundirse con las Helíades, las hermanas de Faetón que lloraron ámbar a orillas del Erídano."},
 {id:"cercafo", n:"Cércafo", rol:"Hijo de Helios", epi:"El que se quedó", gen:"g5", padres:["helios","rodas"],
  r:"Uno de los siete hijos de Helios y Rodas, y el que continúa el linaje en la isla. Sus tres hijos se repartirán el territorio y darán nombre a las tres grandes ciudades rodias."},
 {id:"yaliso", n:"Yáliso", rol:"Héroe epónimo", epi:"El de Yaliso", gen:"g5", padres:["cercafo"],
  r:"Hijo de Cércafo y héroe epónimo de Yaliso, una de las tres ciudades en que se dividió Rodas. La Ilíada nombra a las tres juntas al enumerar las naves rodias."},
 {id:"camiro", n:"Camiro", rol:"Héroe epónimo", epi:"El de Camiros", gen:"g5", padres:["cercafo"],
  r:"Hijo de Cércafo y héroe epónimo de Camiros, en la costa occidental de la isla. Con sus hermanos representa el reparto del territorio entre tres ciudades que compartían culto al Sol."},
 {id:"lindo", n:"Lindo", rol:"Héroe epónimo", epi:"El de Lindos", gen:"g5", padres:["cercafo"],
  r:"Hijo de Cércafo y héroe epónimo de Lindos, la más célebre de las tres ciudades rodias por su acrópolis y su santuario. El reparto entre los tres hermanos explica en clave mítica una división política real de la isla."},
 {id:"lampetia", n:"Lampetía", rol:"Ninfa", epi:"La resplandeciente", gen:"g5", padres:["helios"],
  r:"Hija de Helios y guardiana, junto a su hermana Faetusa, de los rebaños sagrados del Sol en la isla de Trinacria: siete manadas de vacas y siete de ovejas que ni nacen ni mueren. Es ella quien avisa a su padre cuando los compañeros de Odiseo sacrifican las reses, y esa denuncia desencadena el castigo que los deja a todos en el fondo del mar.",
  v:"Su madre es la ninfa Neera. Algunas listas incluyen su nombre entre las Helíades que lloraron a Faetón, que son otras hijas de Helios."},
 {id:"orfeo", n:"Orfeo", rol:"Músico", epi:"El que amansa a las piedras", gen:"g5", padres:["eagro","caliope"], pareja:["euridice-o"],
  r:"Hijo de la musa Calíope y del rey tracio Eagro. Su música detiene los ríos, amansa a las fieras y arrastra a las piedras detrás de él. Baja al inframundo a buscar a su esposa muerta, detiene el remo de Caronte y conmueve a Hades, que se la concede con una condición: no volverse a mirarla hasta salir. Mira atrás a un paso de la luz y la pierde para siempre.",
  v:"Otras tradiciones hacen de Apolo su padre, y de ahí su dominio de la lira. Fue además el nombre bajo el cual circuló toda una corriente religiosa, el orfismo, con sus propios poemas sobre el origen del mundo."}
];
