/* ============================================================
   DATOS DEL ANEXO — este es el unico archivo que necesitas
   tocar para agregar o corregir contenido del libro.
   No hace falta saber programar: copia el formato de una
   entrada existente y cambia el texto entre comillas.

   ERAS         -> los grandes bloques de la cronologia
   CRONOLOGIA   -> cada episodio (era, marca, titulo, resena, ver)
   GENERACIONES -> los bloques del arbol genealogico
   FIGURAS      -> cada personaje (id, n, rol, epi, gen, padres,
                   pareja, r = resena, v = variantes y fuentes)

   El campo "v" es opcional: uselo para discrepancias entre
   fuentes, nombres alternativos y versiones minoritarias. Se
   muestra aparte, en letra mas chica, debajo de la resena.

   Regla unica: el "id" de cada figura debe ser unico y sin
   tildes ni espacios, porque es el que usan "padres",
   "pareja" y "ver" para enlazar unos con otros.
   ============================================================ */

const ERAS = [
 {id:"e1", num:"Era I",  titulo:"Antes del tiempo", sub:"El vacío y los primordiales"},
 {id:"e2", num:"Era II", titulo:"El reino de Crono", sub:"Primera generación divina"},
 {id:"e3", num:"Era III",titulo:"El orden olímpico", sub:"Zeus impone su ley"},
 {id:"e4", num:"Era IV", titulo:"La edad de los héroes", sub:"Mortales con sangre divina"},
 {id:"e5", num:"Era V",  titulo:"Troya y el ocaso", sub:"El fin de la raza heroica"}
];

const CRONOLOGIA = [
 {era:"e1", marca:"Origen", titulo:"El Caos", resena:"No es desorden sino abertura: una sima bostezante donde todavía no hay arriba ni abajo. Hesíodo lo pone primero porque todo lo demás necesita un lugar donde caber.", ver:["caos"]},
 {era:"e1", marca:"Origen", titulo:"Nacen los primordiales", resena:"Del Caos surgen Gea (la tierra), Tártaro (el abismo bajo ella), Eros (la fuerza que une), Érebo (la sombra) y Nix (la noche). Son potencias, no personas: nadie les reza, todos los heredan.", ver:["gea","tartaro","eros","erebo","nix"]},
 {era:"e1", marca:"Origen", titulo:"Gea engendra sola", resena:"Sin unión previa, la tierra produce a Urano (el cielo estrellado), las montañas y Ponto (el mar). Es el primer acto de creación por desdoblamiento: la tierra fabrica aquello que la cubrirá.", ver:["urano","ourea","ponto"]},
 {era:"e1", marca:"Origen", titulo:"Los hijos encerrados", resena:"De Gea y Urano nacen doce titanes, tres cíclopes y tres hecatónquiros de cien brazos. Urano teme a los monstruosos y los devuelve al vientre de su madre, que empieza a fraguar la venganza.", ver:["ciclopes","hecatonquiros"]},
 {era:"e1", marca:"Ruptura", titulo:"La castración de Urano", resena:"Crono, el menor de los titanes, siega a su padre con una hoz de pedernal que Gea le entrega. Unas gotas de sangre caen sobre la tierra y dejan a Gea encinta de tres progenies: las Erinias, los Gigantes y las Melias. De la espuma del mar donde cae el sexo nace, en cambio, Afrodita.", ver:["crono","urano","erinias","gigantes","melias","afrodita"]},

 {era:"e2", marca:"Edad de oro", titulo:"Crono devora a sus hijos", resena:"Advertido de que un hijo suyo lo destronará como él destronó a su padre, Crono traga a cada recién nacido. El ciclo del mito griego se anuncia aquí: ningún poder logra impedir su propio relevo.", ver:["crono","rea"]},
 {era:"e2", marca:"Edad de oro", titulo:"El engaño de Rea", resena:"Rea da a luz a Zeus en secreto en una cueva de Creta y entrega a Crono una piedra envuelta en pañales. El niño crece amamantado por la cabra Amaltea, entre los golpes de los Curetes que ahogan su llanto.", ver:["rea","zeus"]},
 {era:"e2", marca:"Guerra", titulo:"Zeus libera a sus hermanos", resena:"Ya adulto, Zeus hace vomitar a Crono a los cinco hijos devorados: Hestia, Deméter, Hera, Hades y Poseidón. Salen adultos y en orden inverso, así que el hermano menor es también el primogénito.", ver:["zeus","hestia","demeter","hera","hades","poseidon"]},
 {era:"e2", marca:"Guerra", titulo:"La Titanomaquia", resena:"Diez años de guerra entre olímpicos y titanes. Zeus libera del Tártaro a los cíclopes, que le forjan el rayo, el tridente a Poseidón y el casco de invisibilidad a Hades; los hecatónquiros sepultan a los titanes bajo una lluvia de rocas.", ver:["zeus","ciclopes","hecatonquiros"]},
 {era:"e2", marca:"Reparto", titulo:"El sorteo del cosmos", resena:"Los tres hermanos echan suertes: a Zeus el cielo, a Poseidón el mar, a Hades el mundo subterráneo. La tierra y el Olimpo quedan en común, y esa ambigüedad alimentará casi todos los conflictos posteriores.", ver:["zeus","poseidon","hades"]},

 {era:"e3", marca:"Amenaza", titulo:"La Gigantomaquia", resena:"Gea lanza contra los olímpicos a los Gigantes nacidos de la sangre de Urano. Un oráculo advierte que ningún dios puede matarlos sin la ayuda de un mortal: Heracles dispara la flecha que decide la guerra.", ver:["gea","heracles","zeus"]},
 {era:"e3", marca:"Amenaza", titulo:"Tifón contra Zeus", resena:"El último hijo de Gea, con cien cabezas de serpiente, arrasa el Olimpo y llega a arrancarle a Zeus los tendones. Vencido, queda aplastado bajo el Etna, y su aliento sigue saliendo por el cráter.", ver:["zeus","gea"]},
 {era:"e3", marca:"Humanidad", titulo:"El robo del fuego", resena:"Prometeo engaña a Zeus en el reparto del sacrificio y luego roba el fuego para los hombres en una caña hueca. Su castigo es el águila que le devora el hígado cada día en el Cáucaso.", ver:["prometeo","zeus"]},
 {era:"e3", marca:"Humanidad", titulo:"Pandora abre la jarra", resena:"Como represalia, Zeus envía a la primera mujer con una vasija que contiene todos los males. Cuando la abre solo queda dentro la esperanza, y los griegos nunca se pusieron de acuerdo sobre si eso es un consuelo o una condena.", ver:["epimeteo","zeus"]},
 {era:"e3", marca:"Estaciones", titulo:"El rapto de Perséfone", resena:"Hades se lleva a la hija de Deméter al inframundo mientras ella recoge flores en compañía de las oceánides; la madre, buscándola, deja morir toda cosecha. El pacto final —seis granos de granada, unos meses arriba y otros abajo— explica el invierno y funda los misterios de Eleusis.", ver:["hades","persefone","demeter","oceanides"]},
 {era:"e3", marca:"Humanidad", titulo:"El diluvio de Deucalión", resena:"Harto de la edad de bronce, Zeus anega la tierra. Sobreviven Deucalión, hijo de Prometeo, y Pirra, que repueblan el mundo lanzando piedras por encima del hombro: los huesos de la madre tierra se vuelven hombres.", ver:["prometeo","zeus"]},

 {era:"e4", marca:"Generación I", titulo:"Perseo y la Gorgona", resena:"Con las sandalias aladas, el casco de Hades y un escudo pulido como espejo, decapita a Medusa sin mirarla. De su cuello brota Pegaso, y la cabeza cortada seguirá petrificando enemigos hasta terminar en el escudo de Atenea.", ver:["perseo","atenea"]},
 {era:"e4", marca:"Generación II", titulo:"Los doce trabajos de Heracles", resena:"Enloquecido por Hera, mata a su familia; la expiación son doce tareas imposibles al servicio de Euristeo, del león de Nemea al perro Cerbero. Es el único héroe que termina sentado entre los dioses.", ver:["heracles","hera","hesperides"]},
 {era:"e4", marca:"Generación II", titulo:"Teseo y el Minotauro", resena:"Se ofrece como uno de los catorce jóvenes tributados a Creta y mata a la bestia del laberinto guiado por el hilo de Ariadna. Al volver olvida cambiar las velas negras, y su padre Egeo se arroja al mar que lleva su nombre.", ver:["teseo","minos","poseidon"]},
 {era:"e4", marca:"Generación II", titulo:"Los Argonautas", resena:"Jasón reúne a la primera tripulación de héroes para traer el vellocino de oro desde la Cólquide. Lo consigue por la hechicería de Medea, y el precio de esa deuda destruirá después a los dos.", ver:["orfeo","heracles"]},
 {era:"e4", marca:"Generación II", titulo:"La maldición de Tebas", resena:"Edipo resuelve el enigma de la Esfinge sin resolver el suyo: mata a su padre y desposa a su madre. La ciudad arrastrará la culpa hasta la guerra de los Siete contra Tebas y la desobediencia de Antígona.", ver:["dioniso"]},

 {era:"e5", marca:"Chispa", titulo:"La manzana de la discordia", resena:"A las bodas de Peleo y Tetis acuden todos los dioses salvo Eris, que arroja una manzana dedicada a la más bella. La disputa entre Hera, Atenea y Afrodita queda en manos de un pastor troyano.", ver:["eris","afrodita","hera","atenea","aquiles"]},
 {era:"e5", marca:"Chispa", titulo:"El juicio de Paris", resena:"Cada diosa ofrece un soborno: poder, victoria en la guerra o la mujer más bella del mundo. Paris elige a Afrodita, se lleva a Helena de Esparta y arrastra consigo a mil naves.", ver:["afrodita","helena"]},
 {era:"e5", marca:"Guerra", titulo:"Diez años ante Ilión", resena:"La Ilíada no cuenta la guerra entera sino unas semanas del noveno año: la cólera de Aquiles, la muerte de Patroclo y el rescate del cuerpo de Héctor. Los dioses combaten en ambos bandos.", ver:["aquiles","zeus","atenea","apolo"]},
 {era:"e5", marca:"Caída", titulo:"El caballo y el saqueo", resena:"La astucia de Odiseo termina lo que diez años de asedio no pudieron. La ciudad arde, los templos se profanan y esa impiedad condena a los propios vencedores en el viaje de vuelta.", ver:["atenea","poseidon"]},
 {era:"e5", marca:"Regresos", titulo:"Los nostoi y la Odisea", resena:"Casi ningún héroe llega bien a casa: Agamenón cae asesinado al cruzar su umbral y Odiseo tarda otros diez años entre cíclopes, hechiceras y muertos. El regreso resulta más caro que la guerra.", ver:["poseidon","atenea"]},
 {era:"e5", marca:"Final", titulo:"El fin de la edad heroica", resena:"Orestes es absuelto por un tribunal humano y no por los dioses: la venganza cede ante la ley. Los semidioses se extinguen, Eneas huye hacia occidente y comienza la edad de hierro, la nuestra.", ver:["eneas","atenea"]}
];

const GENERACIONES = [
 {id:"g1", titulo:"Primordiales"},
 {id:"gn", titulo:"Prole de la Noche"},
 {id:"gm", titulo:"Estirpe de Ponto"},
 {id:"g2", titulo:"Titanes"},
 {id:"g3", titulo:"Segunda generación titánica"},
 {id:"g4", titulo:"Olímpicos"},
 {id:"g5", titulo:"Héroes y semidioses"}
];

/* padres: ids · pareja: ids (uniones notables) */
const FIGURAS = [
 {id:"caos", n:"Caos", rol:"Primordial", epi:"La sima que se abre", gen:"g1", padres:[],
  r:"El primer principio: un hueco bostezante, sin forma ni límite. No engendra por unión sino por simple aparición, y de él salen la noche y la sombra."},
 {id:"gea", n:"Gea", rol:"Primordial", epi:"La tierra de amplio pecho", gen:"g1", padres:["caos"], pareja:["urano","ponto","tartaro"],
  r:"Suelo firme y madre de casi todo lo que existe. Sin intervención masculina engendra primero a Urano, el mayor y más importante de sus hijos, y a continuación dos rasgos de su propia topografía que pueden entenderse como distintos de ella: las Montañas y el mar profundo, Ponto. Con cada uno de esos dos varones funda después una familia de signo contrario. Unida a Urano levanta la principal, la estirpe de la que saldrán los titanes y, tras ellos, los dioses olímpicos. Unida a Ponto levanta una menor y de naturaleza marítima, poblada de dioses del mar, ninfas y criaturas grotescas que quedarán por necesidad al margen del Olimpo. Es además la conspiradora perpetua: arma a Crono contra Urano, y después a los Gigantes y a Tifón contra Zeus."},
 {id:"tartaro", n:"Tártaro", rol:"Primordial", epi:"El abismo bajo la tierra", gen:"g1", padres:["caos"], pareja:["gea"],
  r:"Tan lejos del suelo como el suelo del cielo: un yunque tardaría nueve días en caer. Es cárcel de los titanes y, con Gea, padre de Tifón."},
 {id:"eros", n:"Eros", rol:"Primordial", epi:"El que afloja los miembros", gen:"g1", padres:["caos"],
  r:"En la versión antigua no es el niño con arco sino la fuerza más vieja del mundo: sin él nada se une y la creación se detiene."},
 {id:"erebo", n:"Érebo", rol:"Primordial", epi:"La tiniebla", gen:"g1", padres:["caos"], pareja:["nix"],
  r:"La oscuridad densa que ocupa el espacio entre la tierra y el mundo de los muertos. Unido a su hermana Nix engendra a Éter y a Hémera, y ahí termina su papel: la restante descendencia de la Noche la concibe ella sola."},
 {id:"nix", n:"Nix", rol:"Primordial", epi:"La noche", gen:"g1", padres:["caos"], pareja:["erebo"],
  r:"De su hermano Érebo tiene solo dos hijos, Éter y Hémera, las dos formas de la luz. Todo el resto de su nutrida descendencia lo engendra sola, sin intervención masculina, y es de signo contrario: el Sueño, la Muerte, las Moiras, la Discordia y los demás poderes que ningún dios puede revocar. Hasta Zeus la respeta; la Ilíada cuenta que se abstuvo de ofenderla por temor."},
 {id:"hemera", n:"Hémera", rol:"Primordial", epi:"El día", gen:"gn", padres:["erebo","nix"],
  r:"La luz diurna en persona, nacida de la tiniebla y de la noche en el mismo parto que su hermano Éter: para los griegos el día procede de lo oscuro y no al revés. Hesíodo las sitúa a ella y a su madre en un mismo umbral que nunca cruzan juntas, saludándose al pasar mientras una entra y la otra sale."},
 {id:"eter", n:"Éter", rol:"Primordial", epi:"La luminosidad de las alturas", gen:"gn", padres:["erebo","nix"],
  r:"El aire superior, purísimo y encendido, que respiran los dioses, frente al aire denso y bajo que respiran los mortales. Hermano de Hémera y nacido con ella del mismo parto, es más sustancia del cielo que personaje con relatos propios:",
  v:"Hesíodo lo nombra y no vuelve a ocuparse de él. Higino invierte el orden y hace de Éter y Hémera los padres de la tierra, el cielo y el mar."},
 {id:"moro", n:"Moro", rol:"Hijo de la Noche", epi:"El destino", gen:"gn", padres:["nix"],
  r:"Encabeza la lista de los hijos que la Noche engendra sola, y Hesíodo lo llama odioso. No es el destino en general sino algo más estrecho y más temible: la muerte ya señalada para un hombre concreto, la que le toca y de la que no hay apelación. Comparte raíz con la moira que cada mortal recibe al nacer."},
 {id:"ker", n:"Ker", rol:"Hija de la Noche", epi:"La Perdición", gen:"gn", padres:["nix"],
  r:"La negra Ker, la ruina que se lleva al hombre en el instante final. En la Ilíada, Zeus pone en la balanza las keres de Aquiles y de Héctor, y el plato que baja decide quién muere.",
  v:"Suele aparecer multiplicada en plural, las Keres, espíritus de la muerte violenta que merodean el campo de batalla y beben la sangre de los caídos."},
 {id:"tanato", n:"Tánato", rol:"Hijo de la Noche", epi:"La Muerte", gen:"gn", padres:["nix"],
  r:"La muerte en persona, inflexible y sin ofrendas: es el único dios al que no se le levantan templos porque no acepta regalos. Hermano de Hipno, con quien transporta el cuerpo de Sarpedón desde Troya hasta Licia en la Ilíada. Sísifo llegó a encadenarlo, y mientras estuvo preso nadie en el mundo pudo morir."},
 {id:"hipno", n:"Hipno", rol:"Hijo de la Noche", epi:"El Sueño", gen:"gn", padres:["nix"],
  r:"Hermano gemelo de Tánato y mucho más benigno: el sueño es la muerte que suelta a su presa cada mañana. En la Ilíada, Hera lo soborna para que adormezca a Zeus en pleno combate, y él acepta solo tras exigir como pago a una de las Gracias. De él nacen los Sueños que visitan a los durmientes."},
 {id:"geras", n:"Geras", rol:"Hijo de la Noche", epi:"La Vejez", gen:"gn", padres:["nix"],
  r:"El envejecer como potencia autónoma y no deseada, hermano de la Muerte y de la Perdición. Apenas tiene relatos, pero la cerámica ática lo representa como un viejo encogido y reseco que forcejea con Heracles, la imagen del héroe peleando contra lo único que no puede vencer."},
 {id:"oneiros", n:"Los Oneiros", rol:"Hijos de la Noche", epi:"Los Sueños", gen:"gn", padres:["nix"],
  r:"La tribu innumerable de los sueños. Salen de dos puertas: los que pasan por la de cuerno se cumplen, los que pasan por la de marfil engañan, y el durmiente no tiene manera de saber por cuál entró el suyo.",
  v:"Hesíodo los cuelga de la Noche; Homero, en cambio, los hace depender de Hipno. Zeus se vale de uno de ellos para mandar a Agamenón un sueño falso al comienzo de la Ilíada."},
 {id:"oizys", n:"Oizys", rol:"Hija de la Noche", epi:"El Dolor", gen:"gn", padres:["nix"],
  r:"La angustia y la miseria sostenidas, el sufrimiento que no es herida sino desgaste. Los romanos la tradujeron como Miseria. No protagoniza mito alguno: su fuerza está justamente en ser el fondo cotidiano contra el que se recortan las hazañas de los héroes."},
 {id:"apate", n:"Apate", rol:"Hija de la Noche", epi:"El Engaño", gen:"gn", padres:["nix"],
  r:"El fraude y la mentira eficaz, hermana de la Discordia y del Dolor. Los griegos no la condenaban sin matices: el engaño que Zeus sufre de Hera, o el que Odiseo emplea en Troya, pertenece al mismo terreno que ella gobierna. Escapa de la jarra de Pandora junto con los demás males."},
 {id:"nemesis", n:"Némesis", rol:"Hija de la Noche", epi:"El castigo merecido", gen:"gn", padres:["nix"],
  r:"No es venganza ni azar, sino la corrección de lo desmedido: reparte a cada uno lo que le corresponde y recorta al que tiene de más o se envanece de más. Persigue sobre todo la soberbia del afortunado.",
  v:"Una tradición la hace madre de Helena: perseguida por Zeus y transformada en oca, puso el huevo que Leda solo habría criado."},
 {id:"eris", n:"Eris", rol:"Hija de la Noche", epi:"La Discordia", gen:"gn", padres:["nix"],
  r:"La querella y la rivalidad. Hesíodo distingue dos: una ruinosa, que alimenta la guerra, y otra provechosa, que empuja al alfarero a competir con el alfarero. Es ella quien, excluida de las bodas de Peleo y Tetis, arroja la manzana que desata la guerra de Troya."},
 {id:"filotes", n:"Filotes", rol:"Hija de la Noche", epi:"La ternura", gen:"gn", padres:["nix"],
  r:"Su nombre significa amistad y afecto, y también el trato amoroso. Es la única de la prole de la Noche que no es un mal, aunque Hesíodo la coloca entre el Engaño y la Vejez: el cariño nace de la misma oscuridad que la discordia, y para los griegos esa vecindad no era una contradicción sino una advertencia."},
 {id:"hesperides", n:"Las Hespérides", rol:"Hijas de la Noche", epi:"Las hijas de la Tarde", gen:"gn", padres:["nix"],
  r:"Grupo de ninfas que habita el jardín de los dioses, en los confines occidentales de la tierra. Custodian allí, con el dragón Ladón, un árbol maravilloso que da manzanas doradas. Su nombre viene de Héspero, la estrella de la tarde, y su lugar es el crepúsculo, ahí donde su madre empieza. Heracles llega hasta ellas en el penúltimo de sus trabajos.",
  v:"Algunas fuentes las sitúan en el lejano norte y no en occidente, y hablan de un bosque entero en lugar de un solo árbol. Suelen contarse tres, pero el número oscila entre dos y siete; los nombres más frecuentes son Hesperaretusa o Hesperia, Eritia o Eritheis, y Egle, todos alusivos a la tarde, al rojo del atardecer y a la claridad del día. Hay tradiciones que las hacen hijas de Atlas en vez de la Noche."},
 {id:"momo", n:"Momo", rol:"Hijo de la Noche", epi:"La burla", gen:"gn", padres:["nix"],
  r:"La censura y el sarcasmo. No combate a nadie: se dedica a encontrarle el defecto a todo, incluso a las obras de los dioses, y por pasarse de mordaz terminó expulsado del Olimpo.",
  v:"Una tradición le atribuye haber sugerido a Zeus la guerra de Troya para aliviar a la Tierra del peso de tantos hombres."},
 {id:"cloto", n:"Cloto", rol:"Hija de la Noche", epi:"La Hilandera", gen:"gn", padres:["nix"],
  r:"La primera de las tres Moiras. Hila el hilo de la vida de cada individuo y lo saca de la rueca en el momento del nacimiento. Como sus hermanas, el arte la representa siempre como una mujer hermosa, mientras la literatura prefiere imaginarla anciana."},
 {id:"laquesis", n:"Láquesis", rol:"Hija de la Noche", epi:"La Repartidora", gen:"gn", padres:["nix"],
  r:"La segunda Moira: mide el hilo que su hermana ha hilado y asigna a cada uno el lote que le toca. Su nombre viene de la porción que se recibe por sorteo, y de ahí que el destino griego se parezca menos a un plan que a un reparto."},
 {id:"atropo", n:"Átropo", rol:"Hija de la Noche", epi:"La Inflexible", gen:"gn", padres:["nix"],
  r:"La tercera y más pequeña de las Moiras, y la que no admite vuelta atrás: corta el hilo con sus tijeras y esa vida termina. Su nombre significa literalmente la que no se deja desviar, ni por súplicas ni por ofrendas ni por los propios dioses."},
 {id:"hijos-eris", n:"Los hijos de Eris", rol:"Prole de la Discordia", epi:"Las fuerzas del conflicto", gen:"gn", padres:["eris"],
  r:"Trabajo, Olvido, Hambre, Penas, Luchas, Muertes, Homicidios, Peleas, Mentiras, Disputas y Desorden: las fuerzas dañinas que brotan de la discordia. Son alegorías antes que personajes, sin relatos propios ni culto, y Hesíodo las enumera de corrido para mostrar hasta dónde se ramifica un solo conflicto. Dos de esa lista sí tienen historia aparte: Ate y Horco."},
 {id:"ate", n:"Ate", rol:"Hija de la Discordia", epi:"La Ofuscación", gen:"gn", padres:["eris"],
  r:"No es el error sino la ceguera que lo precede: el momento en que un hombre pierde el juicio y se lanza a su propia ruina creyendo acertar. Camina sobre las cabezas de los hombres sin que sus pies toquen el suelo. Zeus mismo cayó en sus redes el día del nacimiento de Heracles y, furioso, la arrojó del Olimpo para siempre.",
  v:"Hesíodo la cuenta entre los hijos de Eris; Homero la hace hija de Zeus. En la Ilíada la siguen las Súplicas, cojas y arrugadas, que van detrás curando el daño que ella dejó."},
 {id:"horco", n:"Horco", rol:"Hijo de la Discordia", epi:"El Juramento", gen:"gn", padres:["eris"],
  r:"El juramento hecho castigo. No vela por la palabra dada sino por su quiebra: existe para caer sobre quien jura en falso a sabiendas. Hesíodo cuenta que las Erinias asistieron a su nacimiento, y advierte que el perjurio arruina el linaje entero del que lo comete, no solo al perjuro."},
 {id:"urano", n:"Urano", rol:"Primordial", epi:"El cielo estrellado", gen:"g1", padres:["gea"], pareja:["gea"],
  r:"El mayor de los dos hijos que Gea concibe sin padre, y el más importante: el cielo estrellado, unido después a ella. Encierra a sus hijos monstruosos en el vientre de la tierra y por eso cae bajo la hoz de Crono."},
 {id:"ponto", n:"Ponto", rol:"Primordial", epi:"El mar sin cultivar", gen:"g1", padres:["gea"], pareja:["gea"],
  r:"El mar profundo de olas agitadas, concebido por Gea sin padre como un rasgo de su propia superficie: el mar anterior a Poseidón, sin voluntad ni templos. Unido después a su propia madre engendra a Nereo, Forcis, Ceto, Taumante y Euribia, y con ellos una familia menor de dioses marinos, ninfas y criaturas monstruosas. Es la rama que nunca entra al Olimpo: de ella saldrán los seres que los héroes tendrán que enfrentar."},
 {id:"ourea", n:"Los Ourea", rol:"Primordial", epi:"Las Montañas", gen:"g1", padres:["gea"],
  r:"Las alturas del terreno, nacidas de Gea sin padre en el mismo impulso que Ponto. Son relieve antes que personajes: Hesíodo las nombra como morada grata a las ninfas y no vuelve a ocuparse de ellas, y a diferencia de sus hermanos no engendran linaje alguno. Los autores tardíos llegaron a contarlas y darles nombre monte por monte, empezando por el Olimpo."},
 {id:"erinias", n:"Las Erinias", rol:"Nacidas de la sangre", epi:"Las Vengadoras", gen:"g1", padres:["gea","urano"],
  r:"Gea queda encinta por unas gotas de la sangre de Urano, de modo que nacen ya del primer crimen contra un padre y a eso se dedican: persiguen sin descanso al que derrama sangre de su propia familia y al que rompe un juramento. No escuchan súplicas ni aceptan ofrendas. Son las que acosan a Orestes tras matar a su madre, hasta que un tribunal humano las desarma en Atenas.",
  v:"En la tradición arcaica no tienen nombres propios y su número es indeterminado; recién en época romana queda fijado que son tres y que se llaman Alecto, Tisífona y Megaira. Su filiación tampoco es única: el anexo sigue el nacimiento de la sangre de Urano derramada sobre Gea, pero Esquilo y otros autores, apoyándose en Hesíodo, las hacen hijas de la Noche, lo que encaja bien con su carácter, y Sófocles las presenta como hijas de la Tiniebla, Escoto, y de la Tierra. Fueron identificadas además con las Benévolas, Euménides, y las Venerables, Semnai: diosas de aspecto más amable y de nombre más propicio, porque nombrarlas por lo que son se consideraba peligroso."},
 {id:"gigantes", n:"Los Gigantes", rol:"Nacidos de la sangre", epi:"Los de brillante armadura", gen:"g1", padres:["gea","urano"],
  r:"Segunda progenie concebida de esa misma sangre: guerreros enormes y armados que Gea lanzará después contra los olímpicos. La Gigantomaquia solo puede ganarse con ayuda de un mortal, y ese mortal es Heracles. No deben confundirse con los titanes, que son la generación anterior y pierden otra guerra distinta."},
 {id:"melias", n:"Las Melias", rol:"Nacidas de la sangre", epi:"Las ninfas del fresno", gen:"g1", padres:["gea","urano"],
  r:"Tercera progenie de las gotas caídas sobre la tierra: las ninfas de los fresnos. De la madera de ese árbol se hacían las lanzas, de modo que del mismo derramamiento salen las vengadoras, los guerreros y la materia con que se mata. Una tradición hace nacer de ellas a la raza humana de bronce."},
 {id:"ciclopes", n:"Los Cíclopes", rol:"Primordial", epi:"Brontes, Estéropes y Arges", gen:"g1", padres:["gea","urano"],
  r:"Herreros de un solo ojo, encerrados dos veces y liberados por Zeus. Su agradecimiento cambia la historia: forjan el rayo, el tridente y el casco de invisibilidad."},
 {id:"hecatonquiros", n:"Los Hecatónquiros", rol:"Primordial", epi:"Los de cien brazos", gen:"g1", padres:["gea","urano"],
  r:"Coto, Briareo y Giges, con cincuenta cabezas cada uno. Deciden la Titanomaquia arrojando trescientas rocas a la vez y quedan de guardianes en el Tártaro."},

 {id:"forcis", n:"Forcis", rol:"Dios marino", epi:"El viejo del mar", gen:"gm", padres:["ponto","gea"], pareja:["ceto"],
  r:"Hijo de Ponto y Gea, y uno de los ancianos del mar anteriores a Poseidón. Unido a su hermana Ceto engendra la parte más temible de la rama marina: de los dos salen las Grayas, las Gorgonas y la serpiente que guarda las manzanas de oro. La Odisea nombra un puerto suyo en Ítaca, donde desembarca Odiseo."},
 {id:"ceto", n:"Ceto", rol:"Diosa marina", epi:"El monstruo del mar", gen:"gm", padres:["ponto","gea"], pareja:["forcis"],
  r:"Su nombre designa al gran monstruo marino, la ballena o el cetáceo devorador. Hermana y compañera de Forcis, es la madre de la progenie grotesca del mar: junto a él encabeza el linaje que quedará siempre al margen del Olimpo y que los héroes tendrán que enfrentar."},
 {id:"ladon", n:"Ladón", rol:"Monstruo", epi:"La serpiente del jardín", gen:"gm", padres:["forcis","ceto"],
  r:"Serpiente terrible nacida de Forcis y Ceto. Enroscado al árbol del jardín de los dioses, vigila las manzanas doradas junto a las Hespérides y no duerme jamás. Heracles lo mata, o lo burla, en el penúltimo de sus trabajos, y Hera lo sube al cielo convertido en la constelación del Dragón.",
  v:"Hesíodo lo presenta como hijo de Forcis y Ceto; Apolonio de Rodas lo hace nacer de la propia Gea. Algunas fuentes le atribuyen cien cabezas y todas las voces, y las hay que lo dejan solo dormido en vez de muerto."},
 {id:"crono", n:"Crono", rol:"Titán", epi:"El de mente retorcida", gen:"g2", padres:["gea","urano"], pareja:["rea"],
  r:"El menor y más audaz de los titanes. Derroca a su padre y gobierna la edad de oro, pero devora a sus hijos por miedo a repetir su propio crimen."},
 {id:"rea", n:"Rea", rol:"Titánide", epi:"La madre de los dioses", gen:"g2", padres:["gea","urano"], pareja:["crono"],
  r:"Esposa y hermana de Crono. Salva a Zeus escondiéndolo en Creta y entregando a su marido una piedra envuelta en pañales."},
 {id:"oceano", n:"Océano", rol:"Titán", epi:"El río que rodea el mundo", gen:"g2", padres:["gea","urano"], pareja:["tetis-t"],
  r:"El río que da la vuelta al disco de la tierra y del que procede toda agua. No participa en la guerra contra Zeus y conserva su dominio. Unido a su hermana Tetis engendra dos progenies de tres mil cada una: los ríos y las ninfas del Océano."},
 {id:"tetis-t", n:"Tetis", rol:"Titánide", epi:"Nodriza de las aguas", gen:"g2", padres:["gea","urano"], pareja:["oceano"],
  r:"Madre de todos los cursos de agua dulce y de las tres mil oceánides. Apenas actúa en los relatos: su papel es ser la fuente de la que todo lo que fluye desciende.",
  v:"No debe confundirse con Tetis la nereida, madre de Aquiles: son dos figuras distintas con nombre casi idéntico, Tethys y Thetis en griego."},
 {id:"potamoi", n:"Los Potamoi", rol:"Hijos de Océano", epi:"Los ríos del mundo", gen:"g3", padres:["oceano","tetis-t"],
  r:"Tres mil hijos varones, es decir, incontables: todos los ríos del mundo, que en griego son de género masculino. No son cursos de agua con un dios encima, sino el río mismo entendido como persona, y por eso pueden luchar. Los más nombrados son el Erídano, el Aqueloo, el Alfeo y el Escamandro.",
  v:"De los tres mil, la Teogonía nombra veinticinco, en este orden: Nilo, Alfeo, Erídano, Estrimón, Meandro, Istro, Fasis, Reso, Aqueloo, Neso, Rodio, Haliacmón, Heptáporo, Gránico, Esepo, Simoide, Peneo, Hermo, Ceco, Sangario, Ladón, Partenio, Eveno, Cares y Escamandro. Son ríos reales repartidos por todo el mundo conocido, desde Egipto hasta el Danubio, y varios de ellos —Esepo, Gránico, Simoide y Escamandro— riegan la llanura de Troya y reaparecen en la Ilíada. Ojo con el Ladón de esta lista, un río de Arcadia que no tiene relación con la serpiente del mismo nombre que guarda las manzanas de oro."},
 {id:"eridano", n:"Erídano", rol:"Río", epi:"El río del ámbar", gen:"g3", padres:["oceano","tetis-t"],
  r:"Río del lejano occidente, más imaginado que localizado: los griegos nunca se pusieron de acuerdo sobre cuál era. En sus aguas cae Faetón fulminado tras perder el control del carro del sol, y sus hermanas, convertidas en álamos en la orilla, lloran las lágrimas de ámbar que le dieron fama.",
  v:"Se lo ha identificado con el Po, con el Ródano y con ríos del Báltico, por la ruta del ámbar. También da nombre a una constelación, el río que corre a los pies de Orión."},
 {id:"aqueloo", n:"Aqueloo", rol:"Río", epi:"El mayor de los ríos", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río más grande de Grecia y el más venerado de todos los Potamoi: por él se juraba, y su nombre llegó a usarse para decir simplemente agua. Lucha con Heracles por la mano de Deyanira cambiando de forma —serpiente, toro— hasta que el héroe le arranca un cuerno. Ese cuerno roto se convierte en la cornucopia, el cuerno de la abundancia.",
  v:"Algunas fuentes lo hacen padre de las Sirenas, con una de las Musas."},
 {id:"alfeo", n:"Alfeo", rol:"Río", epi:"El río de Olimpia", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río que pasa junto al santuario de Olimpia, y uno de los dos que Heracles desvía para limpiar los establos de Augías en un solo día. Persigue a la ninfa Aretusa hasta Sicilia; ella es transformada en fuente y él se hunde bajo el mar para mezclar sus aguas con las de ella al otro lado."},
 {id:"escamandro", n:"Escamandro", rol:"Río", epi:"El río de Troya", gen:"g3", padres:["oceano","tetis-t"],
  r:"El río que corre por la llanura de Troya. En la Ilíada se levanta contra Aquiles, harto de que atasque su cauce con cadáveres, y lo persigue con sus crecidas hasta que Hefesto lo hace retroceder con fuego: es la escena donde queda más claro que un río griego es una persona y no un paisaje.",
  v:"Homero dice que los dioses lo llaman Janto, el rubio, y los hombres Escamandro. Ese doble nombre, uno divino y otro humano, aparece varias veces en la Ilíada."},
 {id:"oceanides", n:"Las Oceánides", rol:"Hijas de Océano", epi:"Las ninfas del Océano", gen:"g3", padres:["oceano","tetis-t"],
  r:"Tres mil hijas, tantas como sus hermanos. Sus funciones no se limitan al agua: Hesíodo insiste en que están diseminadas por todas partes, tanto en la tierra como en las profundidades, y señala que cuidan en particular de los más jóvenes. De ellas salen figuras de primer orden como Metis, Clímene, Dione y Estigia. La mayoría de las muchachas que el Himno homérico a Deméter nombra como compañeras de Perséfone, y que estaban con ella recogiendo flores el día del rapto, figuran también en la lista de Hesíodo como oceánides.",
  v:"La Teogonía conserva el catálogo exacto de las cuarenta y una mayores: Acaste, Admete, Anfiro, Asia, Calipso, Calírroe, Cercéis, Clesidra, Clímene, Clitia, Criséis, Dione, Doris, Electra, Estigia, Eudora, Eurínome, Evágoras, Galaxaura, Hipo, Idía, Janto, Melóbosis, Menesto, Metis, Ociroe, Pasítoa, Peito, Petrea, Ploto, Plutón, Polidora, Primno, Rodía, Ródope, Telesto, Tique, Urania, Yanira, Yanta y Zeuxo. Muchos de esos nombres no son más que invenciones poéticas, igual que ocurre con las Nereidas, y algunos son transparentes: Asia da nombre al continente, Peito es la Persuasión, Plutón la Riqueza, Telesto el Éxito y Tique la Buena Fortuna. También se las llama Okeanidai u Okeaninai. Conviene no confundirlas con las Nereidas, ninfas del mar salado nacidas de Nereo, ni con las ninfas de fuentes y arroyos concretos, aunque las fuentes tardías mezclan los tres grupos."},
 {id:"hiperion", n:"Hiperión", rol:"Titán", epi:"El que va por lo alto", gen:"g2", padres:["gea","urano"], pareja:["tea"],
  r:"Titán de la luz celeste. Ni él ni su hermana Tea protagonizan mito alguno: su importancia está entera en los tres hijos que engendran juntos y que traen la luz a los cielos, Helios el Sol, Selene la Luna y Eos la Aurora. La épica homérica y los poemas arcaicos lo nombran sobre todo por eso, como el padre del dios sol. Antes de Apolo, la carrera del sol pertenece a su linaje y no al Olimpo.",
  v:"En Homero el nombre no siempre designa al titán: a veces funciona como epíteto del propio Helios, llamado Helios Hiperión, y a veces como patronímico, Hiperiónida, el hijo de Hiperión. Conviene comprobar en cada pasaje si se habla del padre o del hijo."},
 {id:"tea", n:"Tea", rol:"Titánide", epi:"La Divina", gen:"g2", padres:["gea","urano"], pareja:["hiperion"],
  r:"Su nombre significa simplemente divina. No aparece en ningún relato: su papel es ser la hermana y compañera de Hiperión y la madre de los tres astros. Se le atribuye la vista y el brillo del metal y las piedras preciosas, y los griegos creían que el oro reluce porque ella lo mira.",
  v:"Figuras como Tea y Febe, definidas casi por entero por su nombre y por con quién se unen, parecen inventadas para completar la lista de los doce. A Hesíodo o a algún predecesor suyo no le hacía falta mucha imaginación para producirlas."},
 {id:"ceo", n:"Ceo", rol:"Titán", epi:"El eje del cielo", gen:"g2", padres:["gea","urano"], pareja:["febe"],
  r:"Titán del pilar norte y del intelecto que interroga. Su lugar entre los titanes se explica sobre todo por su descendencia: unido a Febe engendra a Leto, y por ella es el abuelo de dos de las principales divinidades olímpicas, Apolo y Ártemis."},
 {id:"febe", n:"Febe", rol:"Titánide", epi:"La Radiante", gen:"g2", padres:["gea","urano"], pareja:["ceo"],
  r:"Su nombre significa radiante o brillante. Unida a Ceo es la madre de Leto, y fue dueña del oráculo de Delfos antes que Apolo, a quien se lo cede como regalo. De ella toma su nieto el epíteto Febo, que es el que más veces lo nombra en la Ilíada."},
 {id:"crio", n:"Crío", rol:"Titán", epi:"El carnero", gen:"g2", padres:["gea","urano"],
  r:"El más oscuro de los doce: su naturaleza y su origen son un misterio. Ni siquiera su nombre ayuda mucho, porque significa carnero y nadie sabe bien por qué. Solo se le conoce por su descendencia, que domina los vientos y los astros errantes.",
  v:"La asociación con la constelación de Aries y con el pilar sur del cielo es una conjetura tardía, construida a partir del nombre y no de ningún relato antiguo."},
 {id:"japeto", n:"Jápeto", rol:"Titán", epi:"El perforador", gen:"g2", padres:["gea","urano"],
  r:"Padre de Prometeo, Epimeteo y Atlas: la rama titánica que se juega el destino de los mortales. Los griegos lo tenían por antepasado de la humanidad."},
 {id:"temis", n:"Temis", rol:"Titánide", epi:"La ley que no se escribe", gen:"g2", padres:["gea","urano"], pareja:["zeus"],
  r:"Encarna el orden justo y la costumbre. Consejera de Zeus y madre de las Horas, es la única titánide sentada en el Olimpo.",
  v:"Hesíodo se contradice a sí mismo al atribuirle también las Moiras, que antes había hecho nacer de la Noche sola. El anexo sigue esa primera versión."},
 {id:"mnemosine", n:"Mnemósine", rol:"Titánide", epi:"La memoria", gen:"g2", padres:["gea","urano"], pareja:["zeus"],
  r:"Nueve noches con Zeus y nueve Musas: la poesía nace de la memoria, no de la inspiración súbita. Sin ella no habría relato del mito."},

 {id:"helios", n:"Helios", rol:"Titán menor", epi:"El sol", gen:"g3", padres:["hiperion","tea"],
  r:"Hijo de Hiperión y Tea. Cruza el cielo en un carro de cuatro caballos y lo ve todo: es quien delata a Afrodita ante Hefesto y a Hades ante Deméter. En la Odisea, el robo de sus vacas en Trinacria condena a los últimos compañeros de Odiseo.",
  v:"La épica lo llama también Hiperión, por su padre, o Hiperiónida. Más tarde se lo confundirá con Apolo, aunque en las fuentes arcaicas son dioses distintos."},
 {id:"selene", n:"Selene", rol:"Titánide menor", epi:"La luna", gen:"g3", padres:["hiperion","tea"],
  r:"Conduce un carro de plata y ama al pastor Endimión, a quien Zeus concede un sueño eterno para que nunca envejezca."},
 {id:"eos", n:"Eos", rol:"Titánide menor", epi:"La de dedos de rosa", gen:"g3", padres:["hiperion","tea"],
  r:"Abre las puertas del cielo cada mañana. Pidió la inmortalidad para su amante Titono pero olvidó pedir la juventud, y él envejeció sin poder morir."},
 {id:"leto", n:"Leto", rol:"Titánide menor", epi:"La discreta", gen:"g3", padres:["ceo","febe"], pareja:["zeus"],
  r:"Perseguida por Hera, ninguna tierra firme se atreve a acogerla hasta que la isla flotante de Delos la recibe. Allí da a luz a los gemelos arqueros."},
 {id:"prometeo", n:"Prometeo", rol:"Titán menor", epi:"El que piensa antes", gen:"g3", padres:["japeto"],
  r:"Modela a los hombres con barro y les roba el fuego. Conoce el secreto que puede destronar a Zeus y por eso resiste treinta generaciones de tortura sin hablar."},
 {id:"epimeteo", n:"Epimeteo", rol:"Titán menor", epi:"El que piensa después", gen:"g3", padres:["japeto"],
  r:"Reparte todas las cualidades entre los animales y deja al hombre desnudo. Acepta a Pandora pese a la advertencia de su hermano."},
 {id:"atlas", n:"Atlas", rol:"Titán menor", epi:"El que sostiene", gen:"g3", padres:["japeto"],
  r:"Condenado a cargar la bóveda del cielo por su bando en la Titanomaquia. Solo se libra un instante, cuando Heracles se la sostiene para pedirle las manzanas de oro."},

 {id:"eurinome", n:"Eurínome", rol:"Oceánide", epi:"La de ancho dominio", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"De su unión con Zeus nacen las Gracias. Una tradición anterior la hace reina del Olimpo junto a Ofión antes de que Crono los derribara a ambos, de modo que habría gobernado el cielo antes que los titanes. Es también quien recoge a Hefesto en el fondo del mar cuando su madre lo arroja del Olimpo."},
 {id:"gracias", n:"Las Gracias", rol:"Hijas de Zeus", epi:"Las Cárites", gen:"g4", padres:["zeus","eurinome"],
  r:"Aglaya, Eufrósine y Talía: el esplendor, la alegría y la abundancia. Personifican todo lo que hace la vida grata y sin ellas ningún banquete, danza ni obra de arte sale bien. Acompañan habitualmente a Afrodita, y son ellas quienes la visten y perfuman."},
 {id:"peito", n:"Peito", rol:"Oceánide", epi:"La Persuasión", gen:"g3", padres:["oceano","tetis-t"],
  r:"Preside toda forma de persuasión, desde la política hasta la amatoria, y aparece a menudo como ayudante de Afrodita: es la que consigue el sí que la belleza sola no arranca. Los griegos le rendían culto, porque convencer a la asamblea y convencer a una persona les parecían la misma destreza.",
  v:"Hesíodo la cuenta entre las oceánides; otras fuentes la hacen hija de Afrodita o simple epíteto suyo, y en Roma se la identifica con Suada o Suadela."},
 {id:"tique", n:"Tique", rol:"Oceánide", epi:"La Fortuna", gen:"g3", padres:["oceano","tetis-t"],
  r:"Lo que a cada uno le toca sin que lo merezca ni lo pida: el azar, la suerte buena y la mala. Hesíodo apenas la nombra en la lista de las oceánides, pero con el tiempo crece hasta volverse una de las divinidades más veneradas del mundo griego, protectora de ciudades enteras, que la representaban coronada de murallas.",
  v:"Los romanos la identificaron con Fortuna. En época helenística se la asocia a Némesis como pareja de contrarios: una reparte al azar y la otra corrige lo desmedido."},
 {id:"dione", n:"Dione", rol:"Oceánide", epi:"La diosa, en femenino", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"Su nombre es la forma femenina del de Zeus, y a veces aparece como consorte suya: en Dodona, el santuario oracular más antiguo de Grecia, se le rendía culto junto a él en lugar de a Hera. En la Ilíada consuela a Afrodita cuando Diomedes la hiere en combate y la llama hija suya.",
  v:"Esa filiación es la clave de la versión homérica que hace a Afrodita hija de Zeus y Dione, en vez de nacida de la espuma. Hesíodo la cuenta entre las oceánides; otras listas la hacen titánide, hija de Gea y Urano."},
 {id:"calipso", n:"Calipso", rol:"Oceánide", epi:"La que oculta", gen:"g3", padres:["oceano","tetis-t"],
  r:"La ninfa de la isla de Ogigia, que retiene a Odiseo siete años y le ofrece la inmortalidad a cambio de quedarse. Él la rechaza por volver a casa, y ella lo deja marchar solo cuando Hermes se lo ordena de parte de Zeus. Su nombre significa la que esconde o encubre, y eso es exactamente lo que hace con el héroe: lo borra del mundo.",
  v:"Hesíodo la incluye en la lista de las oceánides; la Odisea, en cambio, la hace hija de Atlas."},
 {id:"doris", n:"Doris", rol:"Oceánide", epi:"La dadivosa", gen:"g3", padres:["oceano","tetis-t"], pareja:["nereo"],
  r:"Unida a Nereo, el viejo del mar, es la madre de las cincuenta Nereidas. Su nombre evoca el don o la abundancia que el mar entrega. Por ella la rama de Ponto y la de Océano quedan enlazadas: las ninfas del mar salado descienden a la vez de las dos familias que Gea fundó."},
 {id:"nereo", n:"Nereo", rol:"Dios marino", epi:"El viejo del mar", gen:"gm", padres:["ponto","gea"], pareja:["doris"],
  r:"El primogénito de Ponto y Gea, y el único benévolo de esa estirpe: justo, veraz y sin engaño. Conoce todas las cosas y cambia de forma para no responder, hasta que Heracles lo sujeta y lo obliga a revelar el camino hacia las manzanas de oro. Con Doris engendra a las cincuenta Nereidas."},
 {id:"nereidas", n:"Las Nereidas", rol:"Hijas de Nereo", epi:"Las ninfas del mar salado", gen:"gm", padres:["nereo","doris"],
  r:"Cincuenta ninfas que habitan el fondo del mar y acompañan a los navegantes. La más célebre es Tetis, madre de Aquiles; también están Anfítrite, la reina del mar, y Galatea. Cuando Aquiles llora por Patroclo, todas suben juntas desde las profundidades a consolarlo.",
  v:"Como ocurre con las oceánides, buena parte de sus nombres son invenciones poéticas. No deben confundirse con las Oceánides, hijas de Océano y ninfas de las aguas en general."},
 {id:"anfitrite", n:"Anfítrite", rol:"Nereida", epi:"La reina del mar", gen:"gm", padres:["nereo","doris"], pareja:["poseidon"],
  r:"Unida a Poseidón es la reina del mar y la madre de Tritón. Al principio lo rechazó y huyó a esconderse en los confines del Océano; fue un delfín quien la encontró y la persuadió de volver, y en pago Poseidón lo puso entre las estrellas.",
  v:"La Teogonía la cuenta entre las nereidas, hija de Nereo y Doris, que es la filiación que sigue el anexo. Apolodoro, en cambio, la clasifica como oceánide, hija de Océano y Tetis."},
 {id:"climene", n:"Clímene", rol:"Oceánide", epi:"La de fama célebre", gen:"g3", padres:["oceano","tetis-t"], pareja:["japeto"],
  r:"Unida al titán Jápeto es la madre de Prometeo, Epimeteo, Atlas y Menecio, es decir, de la rama titánica que se juega el destino de los mortales. Una tradición la hace también madre de Faetón con Helios, el muchacho que quiso conducir el carro del sol y fue fulminado."},
 {id:"calirroe", n:"Calírroe", rol:"Oceánide", epi:"La de bella corriente", gen:"g3", padres:["oceano","tetis-t"],
  r:"Unida a Crisaor, el hijo que brotó del cuello de Medusa, es la madre de Gerión, el gigante de tres cuerpos cuyo ganado Heracles roba en el décimo de sus trabajos. Su descendencia la instala de lleno en la rama monstruosa, pese a ser hija de Océano."},
 {id:"perseida", n:"Perseida", rol:"Oceánide", epi:"La compañera de Helios", gen:"g3", padres:["oceano","tetis-t"], pareja:["helios"],
  r:"Unida a Helios es la madre de Circe, la hechicera de Eea, y de Eetes, rey de la Cólquide, además de Pasífae, la reina de Creta que concibe al Minotauro. De ella desciende por tanto casi toda la hechicería que aparece en los relatos griegos."},
 {id:"idia", n:"Idía", rol:"Oceánide", epi:"La que sabe", gen:"g3", padres:["oceano","tetis-t"],
  r:"Esposa de Eetes, el rey de la Cólquide que custodia el vellocino de oro, y madre de Medea. Su nombre alude al saber, lo que encaja con una hija que dominará la hechicería mejor que nadie y decidirá el éxito de los Argonautas."},
 {id:"estigia", n:"Estigia", rol:"Oceánide", epi:"La odiosa", gen:"g3", padres:["oceano","tetis-t"],
  r:"La diosa del río infernal que rodea el mundo de los muertos. Fue la primera en acudir con sus hijos al lado de Zeus en la guerra contra los titanes, y su recompensa fue que todo juramento divino se preste por sus aguas: el dios que jura en falso por Estigia queda un año sin aliento y nueve más apartado del Olimpo.",
  v:"Hesíodo la coloca al final de la lista de las oceánides, y esa posición indica que la tiene por la más importante de todas."},
 {id:"hestia", n:"Hestia", rol:"Olímpica", epi:"El hogar", gen:"g4", padres:["crono","rea"],
  r:"La primogénita devorada y la última en salir. Renuncia a su trono y a todo relato: su presencia es el fuego que no se deja apagar en la casa y en la ciudad."},
 {id:"demeter", n:"Deméter", rol:"Olímpica", epi:"La madre del grano", gen:"g4", padres:["crono","rea"], pareja:["zeus"],
  r:"Enseña la agricultura y controla la fertilidad de la tierra. Su duelo por Perséfone es la única vez que un dios doblega a otro por hambre."},
 {id:"hera", n:"Hera", rol:"Olímpica", epi:"Reina del Olimpo", gen:"g4", padres:["crono","rea"], pareja:["zeus"],
  r:"Diosa del matrimonio legítimo y esposa de un marido que jamás lo respeta. Su cólera persigue a las amantes y a los hijos bastardos, sobre todo a Heracles."},
 {id:"hades", n:"Hades", rol:"Olímpico", epi:"El de mucha riqueza", gen:"g4", padres:["crono","rea"], pareja:["persefone"],
  r:"Señor de los muertos, no dios de la maldad: es inflexible, no cruel. Casi nunca sube al Olimpo y su nombre se evita en voz alta."},
 {id:"poseidon", n:"Poseidón", rol:"Olímpico", epi:"El que sacude la tierra", gen:"g4", padres:["crono","rea"],
  r:"Manda en el mar, los caballos y los terremotos. Pierde el Ática ante Atenea y persigue a Odiseo por haber cegado a su hijo el cíclope."},
 {id:"zeus", n:"Zeus", rol:"Olímpico", epi:"Padre de dioses y hombres", gen:"g4", padres:["crono","rea"], pareja:["hera","demeter","leto","temis","mnemosine","alcmena","danae","leda","europa","semele","maya","metis"],
  r:"Guarda el rayo y el orden del mundo, incluido el juramento y la hospitalidad. Rompe el ciclo de padres derrocados tragando a Metis antes de que le dé un hijo más fuerte que él."},
 {id:"afrodita", n:"Afrodita", rol:"Olímpica", epi:"La nacida de la espuma", gen:"g4", padres:["urano"], pareja:["anquises"],
  r:"Crono arroja al mar los genitales de su padre y de la espuma que se arremolina en torno a ellos surge la diosa, que llega a tierra en Chipre. Nace por tanto de Urano y sin madre, y es más antigua que Zeus y que todos los olímpicos. Su poder no admite excepciones: solo Atenea, Ártemis y Hestia le resisten.",
  v:"Es la versión de Hesíodo, que explica su nombre por la espuma, afrós. Homero en cambio la hace hija de Zeus y de la oceánide Dione, sin nada que ver con la castración."},
 {id:"atenea", n:"Atenea", rol:"Olímpica", epi:"La de ojos de lechuza", gen:"g4", padres:["zeus","metis"],
  r:"Nace armada de la cabeza de Zeus. Es la guerra pensada frente a la carnicería de Ares, y patrona de los héroes que ganan con astucia: Perseo, Heracles, Odiseo."},
 {id:"apolo", n:"Apolo", rol:"Olímpico", epi:"El del arco de plata", gen:"g4", padres:["zeus","leto"],
  r:"Oráculo, música, medicina y peste: cura y mata con la misma flecha. Su templo en Delfos ordena conocerse a uno mismo y no pasarse de la raya."},
 {id:"artemisa", n:"Ártemis", rol:"Olímpica", epi:"La cazadora", gen:"g4", padres:["zeus","leto"],
  r:"Gemela de Apolo y virgen por elección. Protege a las crías y a las jóvenes, y castiga sin apelación a quien invade su bosque: Acteón terminó devorado por sus perros."},
 {id:"ares", n:"Ares", rol:"Olímpico", epi:"El azote de los hombres", gen:"g4", padres:["zeus","hera"], pareja:["afrodita"],
  r:"La guerra como matanza y pánico, sin gloria. Ni su padre lo quiere, y en la Ilíada Atenea lo derriba de un pedrada."},
 {id:"hefesto", n:"Hefesto", rol:"Olímpico", epi:"El herrero cojo", gen:"g4", padres:["hera"], pareja:["afrodita"],
  r:"Único dios que trabaja. Concebido por Hera sin varón y arrojado del Olimpo, se venga con obras maestras: las armas de Aquiles, los autómatas de oro, la red que atrapa a los amantes."},
 {id:"hermes", n:"Hermes", rol:"Olímpico", epi:"El de las sandalias aladas", gen:"g4", padres:["zeus","maya"],
  r:"Mensajero, ladrón, guía de los muertos y patrón de los caminos. El día que nació ya había robado el ganado de Apolo e inventado la lira para pagarle."},
 {id:"dioniso", n:"Dioniso", rol:"Olímpico", epi:"El nacido dos veces", gen:"g4", padres:["zeus","semele"],
  r:"Rescatado del vientre de su madre fulminada y cosido al muslo de Zeus. Trae el vino, el éxtasis y el teatro, y destruye a quien niega su divinidad."},
 {id:"persefone", n:"Perséfone", rol:"Olímpica", epi:"Reina del inframundo", gen:"g4", padres:["zeus","demeter"], pareja:["hades"],
  r:"Muchacha raptada y soberana temible a la vez. Los granos de granada que come la atan al mundo de abajo y reparten el año entre su madre y su esposo."},
 {id:"metis", n:"Metis", rol:"Oceánide", epi:"La astucia", gen:"g3", padres:["oceano","tetis-t"], pareja:["zeus"],
  r:"Oceánide, primera esposa de Zeus y quien le dio la pócima que hizo vomitar a Crono. Él la traga estando embarazada, y así la inteligencia queda dentro del poder."},
 {id:"maya", n:"Maya", rol:"Pléyade", epi:"La mayor de las Pléyades", gen:"g4", padres:["atlas"], pareja:["zeus"],
  r:"Hija de Atlas, vive apartada en una cueva de Arcadia. Madre de Hermes, a quien encuentra fuera de la cuna la misma noche en que lo dio a luz."},
 {id:"semele", n:"Sémele", rol:"Mortal", epi:"La princesa tebana", gen:"g4", padres:[], pareja:["zeus"],
  r:"Engañada por Hera, pide ver a Zeus en su forma verdadera y el rayo la calcina. Su hijo Dioniso la rescatará después del Hades y la hará inmortal."},

 {id:"perseo", n:"Perseo", rol:"Héroe", epi:"El matador de Medusa", gen:"g5", padres:["zeus","danae"],
  r:"Concebido en una lluvia de oro dentro de una torre. Es el primer héroe de la estirpe de Zeus y el bisabuelo de Heracles: casi todos los linajes heroicos pasan por él."},
 {id:"danae", n:"Dánae", rol:"Mortal", epi:"La encerrada", gen:"g5", padres:[], pareja:["zeus"],
  r:"Su padre la aísla para evitar un oráculo y consigue justo lo contrario. Echada al mar en un arca con su hijo, sobrevive en la isla de Sérifos."},
 {id:"heracles", n:"Heracles", rol:"Héroe", epi:"La gloria de Hera", gen:"g5", padres:["zeus","alcmena"],
  r:"El más fuerte y el más castigado. Sus doce trabajos limpian el mundo de monstruos, y tras morir por la túnica envenenada de Neso es el único mortal admitido entre los dioses."},
 {id:"alcmena", n:"Alcmena", rol:"Mortal", epi:"La reina de Tirinto", gen:"g5", padres:[], pareja:["zeus"],
  r:"Zeus la visita con la forma de su marido y alarga la noche al triple. De ese engaño nace Heracles, y de la misma noche su hermano mortal Ificles."},
 {id:"helena", n:"Helena", rol:"Semidiosa", epi:"La de Esparta", gen:"g5", padres:["zeus","leda"],
  r:"Nacida de un huevo tras la visita de Zeus en forma de cisne. Su fuga con Paris desata la guerra de Troya, aunque una versión sostiene que solo viajó allí un fantasma suyo."},
 {id:"leda", n:"Leda", rol:"Mortal", epi:"La reina de Esparta", gen:"g5", padres:[], pareja:["zeus"],
  r:"Madre de Helena y de los Dioscuros. Sus hijos nacen mezclados, unos mortales y otros divinos, según de quién sean esa misma noche."},
 {id:"minos", n:"Minos", rol:"Rey", epi:"El juez de los muertos", gen:"g5", padres:["zeus","europa"],
  r:"Rey de Creta y dueño del laberinto. Oculta al Minotauro nacido del castigo de Poseidón y termina, tras morir, juzgando a las almas en el inframundo."},
 {id:"europa", n:"Europa", rol:"Mortal", epi:"La raptada por el toro", gen:"g5", padres:[], pareja:["zeus"],
  r:"Princesa fenicia llevada a Creta a lomos de un toro blanco. Su nombre acabó designando todo un continente y su hermano Cadmo fundó Tebas buscándola."},
 {id:"teseo", n:"Teseo", rol:"Héroe", epi:"El sinoicista de Atenas", gen:"g5", padres:["poseidon"],
  r:"Hijo de un padre doble, Egeo y Poseidón. Mata al Minotauro, unifica el Ática y encarna al héroe convertido en rey y legislador."},
 {id:"aquiles", n:"Aquiles", rol:"Héroe", epi:"El de los pies ligeros", gen:"g5", padres:[],
  r:"Hijo de Peleo y la nereida Tetis, invulnerable salvo en el talón. Elige a sabiendas la vida corta con gloria eterna sobre la larga y olvidada."},
 {id:"eneas", n:"Eneas", rol:"Héroe", epi:"El piadoso", gen:"g5", padres:["afrodita","anquises"],
  r:"Escapa de Troya en llamas cargando a su padre y llevando de la mano a su hijo. Su viaje hacia occidente convierte el final griego en el comienzo de Roma."},
 {id:"anquises", n:"Anquises", rol:"Mortal", epi:"El pastor del Ida", gen:"g5", padres:[], pareja:["afrodita"],
  r:"Amado por Afrodita y advertido de no jactarse jamás de ello. Habló, y quedó lisiado; su hijo tendría que sacarlo a hombros de la ciudad en ruinas."},
 {id:"orfeo", n:"Orfeo", rol:"Héroe", epi:"El que amansa a las piedras", gen:"g5", padres:[],
  r:"Hijo de la musa Calíope. Su música detiene el remo de Caronte y conmueve a Hades, pero mira atrás a un paso de la salida y pierde a Eurídice para siempre."}
];
